"""V3.1 persistent-core closure and condition-aligned view scoring."""
from __future__ import annotations

from itertools import combinations
from typing import Any

import numpy as np
from sklearn.metrics import adjusted_rand_score, f1_score, roc_auc_score

from suica_core.v8_incidence_incremental import (
    IncrementalSpec,
    EnumerationCapError,
    _core_jaccard,
    _cores_overlap,
    _inclusion_maximal_cores,
    _pair_core_scores,
    _pair_truth,
    _predicted_labels,
    _specificity,
    _uncertainty_radius,
    exact_maximal_hyperedges,
    pairwise_whole_map_distances,
)
from suica_core.v8_incidence_multiplicity import verified_hyperedges


class CandidateClosureCapError(RuntimeError):
    """Raised when persistent subset intersection closure is too large."""


def intersection_closed_candidates(
    grids: list[list[list[list[tuple[int, ...]]]]],
    *,
    cap: int,
) -> set[frozenset[int]]:
    """Return all size-3+ intersections generated by observed hyperedges."""
    candidates = {
        frozenset(edge)
        for view in grids
        for condition in view
        for radius_edges in condition
        for edge in radius_edges
        if len(edge) >= 3
    }
    items = list(candidates)
    index = 0
    while index < len(items):
        current = items[index]
        for previous in items[:index]:
            intersection = current & previous
            if len(intersection) < 3 or intersection in candidates:
                continue
            candidates.add(intersection)
            items.append(intersection)
            if len(candidates) > cap:
                raise CandidateClosureCapError(
                    f"candidate intersection closure exceeded cap {cap}"
                )
        index += 1
    return candidates


def condition_aligned_core_scores(
    grids: list[list[list[list[tuple[int, ...]]]]],
    *,
    authors: int,
    closure_cap: int,
    threshold: float,
) -> tuple[
    dict[frozenset[int], float],
    list[dict[frozenset[int], float]],
]:
    """Mine all threshold-passing cores with aligned cross-view support.

    Support is anti-monotone under set inclusion: adding an author cannot
    create a supporting edge in a cell where the smaller set had none.
    Apriori expansion from all triples therefore recovers every core that can
    pass ``threshold`` without materializing the full intersection lattice.
    """
    views = len(grids)
    conditions = len(grids[0])
    radii = len(grids[0][0])
    denominator = conditions * radii
    per_view: list[dict[frozenset[int], float]] = [
        {} for _ in range(views)
    ]
    joint: dict[frozenset[int], float] = {}

    def score_frontier(
        frontier: set[frozenset[int]],
        *,
        size: int,
    ) -> set[frozenset[int]]:
        ordered = sorted(
            frontier,
            key=lambda item: tuple(sorted(item)),
        )
        lookup = {
            candidate: index
            for index, candidate in enumerate(ordered)
        }
        totals = np.zeros((views, len(ordered)), dtype=float)
        joint_totals = np.zeros(len(ordered), dtype=float)
        for condition in range(conditions):
            for radius_index in range(radii):
                support = np.zeros(
                    (views, len(ordered)),
                    dtype=float,
                )
                for view in range(views):
                    for edge in grids[view][condition][radius_index]:
                        if len(edge) < size:
                            continue
                        specificity = _specificity(authors, len(edge))
                        if specificity <= 0.0:
                            continue
                        for subset in combinations(edge, size):
                            index = lookup.get(frozenset(subset))
                            if index is not None:
                                support[view, index] = max(
                                    support[view, index],
                                    specificity,
                                )
                totals += support
                joint_totals += np.min(support, axis=0)
        frequent: set[frozenset[int]] = set()
        for index, candidate in enumerate(ordered):
            for view in range(views):
                per_view[view][candidate] = (
                    totals[view, index] / denominator
                )
            joint[candidate] = joint_totals[index] / denominator
            if joint[candidate] >= threshold:
                frequent.add(candidate)
        return frequent

    frontier = {
        frozenset(candidate)
        for candidate in combinations(range(authors), 3)
    }
    evaluated = 0
    size = 3
    while frontier:
        evaluated += len(frontier)
        if evaluated > closure_cap:
            raise CandidateClosureCapError(
                "thresholded candidate search exceeded cap "
                f"{closure_cap}"
            )
        frequent = score_frontier(frontier, size=size)
        size += 1
        if len(frequent) < 2 or size > authors:
            break
        frequent_lookup = set(frequent)
        next_frontier: set[frozenset[int]] = set()
        frequent_list = sorted(
            frequent,
            key=lambda item: tuple(sorted(item)),
        )
        for left_index, left in enumerate(frequent_list):
            for right in frequent_list[left_index + 1:]:
                merged = left | right
                if len(merged) != size:
                    continue
                if all(
                    frozenset(subset) in frequent_lookup
                    for subset in combinations(sorted(merged), size - 1)
                ):
                    next_frontier.add(merged)
        frontier = next_frontier
    return joint, per_view


def _simple_local_scores(
    views: np.ndarray,
    radius: np.ndarray,
) -> dict[str, np.ndarray]:
    aggregate = views.mean(axis=0)
    authors = aggregate.shape[0]
    upper = np.triu_indices(authors, 1)
    delta = aggregate[upper[0]] - aggregate[upper[1]]
    distance = np.linalg.norm(delta, axis=-1)
    scaled = distance / np.maximum(radius[None, :], 1e-8)
    minimum = -np.min(scaled, axis=1)
    soft = np.mean(np.exp(-0.5 * scaled**2), axis=1)

    recurrence = np.zeros(len(upper[0]), dtype=float)
    pair_lookup = {
        (int(left), int(right)): index
        for index, (left, right) in enumerate(
            zip(upper[0], upper[1], strict=True)
        )
    }
    for condition in range(aggregate.shape[1]):
        points = aggregate[:, condition]
        matrix = np.linalg.norm(
            points[:, None, :] - points[None, :, :],
            axis=-1,
        )
        np.fill_diagonal(matrix, np.inf)
        nearest = np.argsort(matrix, axis=1)[:, :5]
        neighbor_sets = [
            set(int(item) for item in row)
            for row in nearest
        ]
        for left, right in zip(upper[0], upper[1], strict=True):
            if (
                int(right) in neighbor_sets[int(left)]
                and int(left) in neighbor_sets[int(right)]
            ):
                recurrence[pair_lookup[(int(left), int(right))]] += 1.0
    recurrence /= aggregate.shape[1]
    return {
        "minimum_same_condition": minimum,
        "soft_local_kernel": soft,
        "neighbor_recurrence": recurrence,
    }


def analyze_incidence_population_v31(
    views: np.ndarray,
    labels: np.ndarray,
    *,
    spec: IncrementalSpec,
    candidate_closure_cap: int,
) -> dict[str, Any]:
    """Estimate condition-aligned persistent cores with subset closure."""
    radius = _uncertainty_radius(views)
    grids: list[list[list[list[tuple[int, ...]]]]] = []
    exact_sets = 0
    approximate_sets = 0
    matched_sets = 0
    enumeration_nodes = 0
    try:
        for view in views:
            view_grid = []
            for condition in range(spec.conditions):
                condition_grid = []
                for epsilon in spec.epsilon_grid:
                    current_radius = float(epsilon * radius[condition])
                    exact, diagnostics = exact_maximal_hyperedges(
                        view[:, condition],
                        radius=current_radius,
                        node_cap=spec.enumeration_node_cap,
                    )
                    approximate = [
                        edge for edge in verified_hyperedges(
                            view[:, condition],
                            epsilon=current_radius,
                        )
                        if len(edge) >= 3
                    ]
                    exact_lookup = {frozenset(item) for item in exact}
                    approximate_lookup = {
                        frozenset(item) for item in approximate
                    }
                    exact_sets += len(exact_lookup)
                    approximate_sets += len(approximate_lookup)
                    matched_sets += len(
                        exact_lookup & approximate_lookup
                    )
                    enumeration_nodes += (
                        diagnostics["bron_kerbosch_nodes"]
                        + diagnostics["split_nodes"]
                    )
                    condition_grid.append(exact)
                view_grid.append(condition_grid)
            grids.append(view_grid)
        scores, per_view_scores = condition_aligned_core_scores(
            grids,
            authors=spec.authors,
            closure_cap=candidate_closure_cap,
            threshold=spec.core_persistence_threshold,
        )
    except EnumerationCapError as error:
        return {
            "status": "REFUSE_ENUMERATION_CAP",
            "refusal_reason": str(error),
        }
    except CandidateClosureCapError as error:
        return {
            "status": "REFUSE_CANDIDATE_CLOSURE_CAP",
            "refusal_reason": str(error),
        }

    cores = _inclusion_maximal_cores(
        scores,
        threshold=spec.core_persistence_threshold,
    )
    ambiguity = _cores_overlap(cores)
    per_view_cores = [
        _inclusion_maximal_cores(
            view_scores,
            threshold=spec.core_persistence_threshold,
        )
        for view_scores in per_view_scores
    ]
    selected = [] if ambiguity else cores
    coverage = (
        len(set().union(*selected)) / spec.authors
        if selected else 0.0
    )
    group_claim = bool(
        len(selected) >= 2
        and coverage >= spec.minimum_group_coverage
    )
    predicted = _predicted_labels(spec.authors, selected)
    upper = np.triu_indices(spec.authors, 1)
    predicted_pairs = (
        predicted[upper[0]] == predicted[upper[1]]
    ).astype(int)
    truth = _pair_truth(labels)
    pair_scores = _pair_core_scores(scores, spec.authors)
    whole_scores = -pairwise_whole_map_distances(views.mean(axis=0))
    local_scores = _simple_local_scores(views, radius)
    return {
        "status": (
            "REFUSE_CORE_AMBIGUITY"
            if ambiguity
            else "ESTIMATE_READY"
        ),
        "refused": ambiguity,
        "group_claim": group_claim,
        "coverage": coverage,
        "selected_cores": [
            sorted(int(item) for item in core)
            for core in selected
        ],
        "candidate_core_count": len(scores),
        "incidence_auc": float(roc_auc_score(truth, pair_scores)),
        "whole_map_auc": float(roc_auc_score(truth, whole_scores)),
        "minimum_same_condition_auc": float(roc_auc_score(
            truth,
            local_scores["minimum_same_condition"],
        )),
        "soft_local_kernel_auc": float(roc_auc_score(
            truth,
            local_scores["soft_local_kernel"],
        )),
        "neighbor_recurrence_auc": float(roc_auc_score(
            truth,
            local_scores["neighbor_recurrence"],
        )),
        "group_f1": float(f1_score(
            truth,
            predicted_pairs,
            zero_division=0,
        )),
        "group_ari": float(adjusted_rand_score(labels, predicted)),
        "cross_view_core_jaccard": _core_jaccard(
            selected,
            per_view_cores,
        ),
        "pair_scores": pair_scores.tolist(),
        "whole_map_scores": whole_scores.tolist(),
        "pair_truth": truth.tolist(),
        "enumeration_nodes": enumeration_nodes,
        "exact_hyperedge_sets": exact_sets,
        "approximate_hyperedge_sets": approximate_sets,
        "approximate_precision": (
            matched_sets / approximate_sets
            if approximate_sets else 1.0
        ),
        "approximate_recall": (
            matched_sets / exact_sets
            if exact_sets else 1.0
        ),
    }


def analyze_counterfactual_pair_v31(
    pair: dict[str, Any],
    *,
    spec: IncrementalSpec,
    candidate_closure_cap: int,
    permutation_seed: int,
) -> dict[str, Any]:
    """Analyze one V3.1 positive/counterfactual population pair."""
    positive = analyze_incidence_population_v31(
        pair["positive_views"],
        pair["labels"],
        spec=spec,
        candidate_closure_cap=candidate_closure_cap,
    )
    negative = analyze_incidence_population_v31(
        pair["negative_views"],
        pair["labels"],
        spec=spec,
        candidate_closure_cap=candidate_closure_cap,
    )
    cap_statuses = {
        "REFUSE_ENUMERATION_CAP",
        "REFUSE_CANDIDATE_CLOSURE_CAP",
    }
    if (
        positive["status"] in cap_statuses
        or negative["status"] in cap_statuses
    ):
        return {
            "status": (
                positive["status"]
                if positive["status"] in cap_statuses
                else negative["status"]
            ),
            "positive": positive,
            "negative": negative,
        }
    permutation = np.random.default_rng(permutation_seed).permutation(
        pair["labels"]
    )
    permutation_auc = float(roc_auc_score(
        _pair_truth(permutation),
        np.asarray(positive["pair_scores"], dtype=float),
    ))
    return {
        "status": "ESTIMATE_READY",
        "pair_id": pair["pair_id"],
        "positive_world": pair["positive_world"],
        "negative_world": pair["negative_world"],
        "oracle_distance_relative_error": (
            pair["oracle_distance_relative_error"]
        ),
        "fitted_distance_relative_error": (
            pair["fitted_distance_relative_error"]
        ),
        "orthogonal_mapping_error": pair["orthogonal_mapping_error"],
        "positive": positive,
        "negative": negative,
        "incremental_auc": (
            float(positive["incidence_auc"])
            - float(positive["whole_map_auc"])
        ),
        "permutation_auc": permutation_auc,
        "chaining_error": bool(
            pair["pair_id"] == "CF2"
            and negative["group_claim"]
        ),
    }
