"""Permutation-orbit decomposition of event-set geometry and observed phase.

The module treats an ordered four-event path as two distinct mathematical
objects:

``G_set``
    The covariance generated by all 4! orderings of a fixed event multiset.

``C_phase``
    Replicated covariance of the observed ordering after regularized
    within-orbit whitening.

Neither object is a psychological construct.  ``C_phase`` is sequence
sensitive only if it exceeds the complete conditional permutation null.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd

from suica_core.v8_order_statistic_null import ExactPermutationPanel
from suica_core.v8_orientation_overlap import (
    _eigensystem,
    _haar_null,
    orientation_metrics,
)
from suica_core.v8_support_containment import _stable_indices


@dataclass(frozen=True)
class OrbitPhaseSpec:
    """Frozen numerical choices for orbit standardization and set overlap."""

    ridge_ratio: float = 0.10
    rank: int = 10
    bootstrap_draws: int = 199
    rotation_draws: int = 499
    block_sizes: tuple[int, ...] = (64, 64, 16, 8)
    seed: int = 20260813

    def __post_init__(self) -> None:
        if not 0 < self.ridge_ratio <= 1:
            raise ValueError("ridge_ratio must lie in (0, 1].")
        if self.rank < 2:
            raise ValueError("rank must be at least two.")
        if min(self.bootstrap_draws, self.rotation_draws) < 19:
            raise ValueError("Resampling budgets must be at least 19.")
        if not self.block_sizes or any(size < 1 for size in self.block_sizes):
            raise ValueError("block_sizes must contain positive integers.")


@dataclass(frozen=True)
class OrbitPhasePanel:
    """One exact permutation panel in a shared gauge and orbit coordinates."""

    standardized: ExactPermutationPanel
    phase: ExactPermutationPanel
    diagnostics: pd.DataFrame


def fit_shared_orbit_scale(
    left: ExactPermutationPanel,
    right: ExactPermutationPanel,
    *,
    salt: str,
) -> np.ndarray:
    """Fit an equal-corpus, equal-author robust D0 diagonal scale."""
    left_mask = left.metadata["split"].eq("D0").to_numpy()
    right_mask = right.metadata["split"].eq("D0").to_numpy()
    left_ids = left.metadata.loc[left_mask, "author_id"].astype(str).to_numpy()
    right_ids = right.metadata.loc[right_mask, "author_id"].astype(str).to_numpy()
    count = min(len(left_ids), len(right_ids))
    if count < 8:
        raise ValueError("At least eight D0 authors per corpus are required.")
    left_rows = left.residuals[left_mask][
        _stable_indices(left_ids, count, salt=f"{salt}-left")
    ]
    right_rows = right.residuals[right_mask][
        _stable_indices(right_ids, count, salt=f"{salt}-right")
    ]
    pooled = np.concatenate([left_rows, right_rows], axis=0).reshape(
        -1,
        left.residuals.shape[-1],
    )
    median = np.median(pooled, axis=0)
    mad = 1.4826 * np.median(np.abs(pooled - median), axis=0)
    q25, q75 = np.quantile(pooled, (0.25, 0.75), axis=0)
    iqr = (q75 - q25) / 1.349
    standard = pooled.std(axis=0)
    scale = np.where(mad > 1e-8, mad, np.where(iqr > 1e-8, iqr, standard))
    return np.where(scale > 1e-8, scale, 1.0)


def _regularized_orbit_coordinates(
    orbit: np.ndarray,
    *,
    ridge_ratio: float,
) -> tuple[np.ndarray, dict[str, float]]:
    """Return scale-free coordinates of every point in one permutation orbit."""
    values = np.asarray(orbit, dtype=float)
    values = values - values.mean(axis=0, keepdims=True)
    left, singular, right = np.linalg.svd(values, full_matrices=False)
    tolerance = (
        np.finfo(float).eps
        * max(values.shape)
        * max(float(singular[0]), 1.0)
    )
    keep = singular > tolerance
    if not np.any(keep):
        return np.zeros_like(values), {
            "orbit_rank": 0,
            "effective_rank": 0.0,
            "condition_number": np.nan,
        }
    eigenvalues = singular[keep] ** 2 / len(values)
    ridge = ridge_ratio * float(eigenvalues.mean())
    gain = singular[keep] / np.sqrt(eigenvalues + ridge)
    coordinates = (left[:, keep] * gain) @ right[keep]
    probabilities = eigenvalues / eigenvalues.sum()
    return coordinates, {
        "orbit_rank": int(np.sum(keep)),
        "effective_rank": float(1.0 / np.sum(probabilities**2)),
        "condition_number": float(eigenvalues.max() / eigenvalues.min()),
    }


def build_orbit_phase_panel(
    panel: ExactPermutationPanel,
    *,
    scale: np.ndarray,
    ridge_ratio: float,
) -> OrbitPhasePanel:
    """Apply a shared gauge and local regularized orbit whitening."""
    scale = np.asarray(scale, dtype=float)
    if scale.shape != (panel.residuals.shape[-1],):
        raise ValueError("scale does not match the feature dimension.")
    standardized_values = panel.residuals / scale[None, None, None, :]
    phase = np.empty_like(standardized_values, dtype=np.float32)
    rows: list[dict[str, Any]] = []
    for author_index in range(len(panel.metadata)):
        for replicate in range(2):
            coordinates, diagnostic = _regularized_orbit_coordinates(
                standardized_values[author_index, replicate],
                ridge_ratio=ridge_ratio,
            )
            phase[author_index, replicate] = coordinates.astype(np.float32)
            rows.append(
                {
                    "corpus": panel.metadata.iloc[author_index]["corpus"],
                    "author_id": panel.metadata.iloc[author_index]["author_id"],
                    "split": panel.metadata.iloc[author_index]["split"],
                    "replicate": replicate,
                    **diagnostic,
                }
            )
    standardized = ExactPermutationPanel(
        metadata=panel.metadata.copy(),
        residuals=standardized_values.astype(np.float32),
    )
    phase_panel = ExactPermutationPanel(
        metadata=panel.metadata.copy(),
        residuals=phase,
    )
    return OrbitPhasePanel(
        standardized=standardized,
        phase=phase_panel,
        diagnostics=pd.DataFrame(rows),
    )


def _split_orbits(
    panel: ExactPermutationPanel,
    split: str,
) -> tuple[np.ndarray, np.ndarray]:
    mask = panel.metadata["split"].eq(split).to_numpy()
    return (
        panel.residuals[mask],
        panel.metadata.loc[mask, "author_id"].astype(str).to_numpy(),
    )


def _aligned_orbits(
    left: ExactPermutationPanel,
    right: ExactPermutationPanel,
    split: str,
    *,
    salt: str,
) -> tuple[np.ndarray, np.ndarray]:
    left_rows, left_ids = _split_orbits(left, split)
    right_rows, right_ids = _split_orbits(right, split)
    count = min(len(left_rows), len(right_rows))
    return (
        left_rows[_stable_indices(left_ids, count, salt=f"{salt}-left")],
        right_rows[_stable_indices(right_ids, count, salt=f"{salt}-right")],
    )


def mean_orbit_covariance(orbits: np.ndarray) -> np.ndarray:
    """Average exact within-orbit covariance over authors and replicates."""
    values = np.asarray(orbits, dtype=float)
    if values.ndim != 4:
        raise ValueError("orbits must have author x replicate x order x feature.")
    return np.einsum(
        "arpi,arpj->ij",
        values,
        values,
        optimize=True,
    ) / max(1, values.shape[0] * values.shape[1] * values.shape[2])


def _set_metrics(
    left: np.ndarray,
    right: np.ndarray,
    *,
    rank: int,
    weights: np.ndarray,
) -> dict[str, float]:
    left_values, left_vectors = _eigensystem(mean_orbit_covariance(left))
    right_values, right_vectors = _eigensystem(mean_orbit_covariance(right))
    if min(
        int(np.sum(left_values > 1e-12)),
        int(np.sum(right_values > 1e-12)),
    ) < rank:
        raise ValueError("SET_GEOMETRY_RANK_UNDERRESOLVED")
    return orientation_metrics(
        left_vectors[:, :rank],
        right_vectors[:, :rank],
        weights,
        weights,
    )


def _block_haar_null(
    left_vectors: np.ndarray,
    right_vectors: np.ndarray,
    weights: np.ndarray,
    *,
    block_sizes: tuple[int, ...],
    draws: int,
    rng: np.random.Generator,
) -> dict[str, np.ndarray]:
    """Rotate the right system within frozen feature-family blocks."""
    dimension = left_vectors.shape[0]
    if sum(block_sizes) != dimension:
        raise ValueError("block_sizes do not cover the feature dimension.")
    result = {
        "hs": np.empty(draws, dtype=float),
        "fidelity": np.empty(draws, dtype=float),
    }
    boundaries = np.cumsum((0, *block_sizes))
    for draw in range(draws):
        rotated = np.empty_like(right_vectors)
        for start, stop in zip(boundaries[:-1], boundaries[1:]):
            orthogonal, triangular = np.linalg.qr(
                rng.normal(size=(stop - start, stop - start)),
            )
            signs = np.where(np.diag(triangular) < 0, -1.0, 1.0)
            orthogonal = orthogonal * signs[None, :]
            rotated[start:stop] = (
                orthogonal @ right_vectors[start:stop]
            )
        metrics = orientation_metrics(
            left_vectors,
            rotated,
            weights,
            weights,
        )
        for metric in result:
            result[metric][draw] = metrics[metric]
    return result


def evaluate_set_geometry_overlap(
    left: ExactPermutationPanel,
    right: ExactPermutationPanel,
    *,
    spec: OrbitPhaseSpec,
) -> dict[str, Any]:
    """Evaluate cross-corpus overlap of order-opportunity geometry."""
    d0_left, d0_right = _aligned_orbits(
        left,
        right,
        "D0",
        salt=f"v8-orbit-set-d0-{spec.seed}",
    )
    left_values, _ = _eigensystem(mean_orbit_covariance(d0_left))
    right_values, _ = _eigensystem(mean_orbit_covariance(d0_right))
    if min(
        int(np.sum(left_values > 1e-12)),
        int(np.sum(right_values > 1e-12)),
    ) < spec.rank:
        return {
            "status": "SET_GEOMETRY_RANK_UNDERRESOLVED",
            "cells": pd.DataFrame(),
        }
    weights = np.sqrt(
        np.clip(left_values[: spec.rank], 0.0, None)
        * np.clip(right_values[: spec.rank], 0.0, None)
    )
    weights = weights / weights.sum()
    rng = np.random.default_rng(spec.seed)
    rows = []
    null_by_cell: dict[tuple[str, str], np.ndarray] = {}
    block_null_by_cell: dict[tuple[str, str], np.ndarray] = {}
    bootstrap_by_cell: dict[tuple[str, str], np.ndarray] = {}
    for split in ("D1", "D2"):
        left_rows, right_rows = _aligned_orbits(
            left,
            right,
            split,
            salt=f"v8-orbit-set-{split}-{spec.seed}",
        )
        metrics = _set_metrics(
            left_rows,
            right_rows,
            rank=spec.rank,
            weights=weights,
        )
        _, left_vectors = _eigensystem(mean_orbit_covariance(left_rows))
        _, right_vectors = _eigensystem(mean_orbit_covariance(right_rows))
        null = _haar_null(
            left_vectors[:, : spec.rank],
            weights,
            weights,
            draws=spec.rotation_draws,
            rng=rng,
        )
        block_null = _block_haar_null(
            left_vectors[:, : spec.rank],
            right_vectors[:, : spec.rank],
            weights,
            block_sizes=tuple(spec.block_sizes),
            draws=spec.rotation_draws,
            rng=rng,
        )
        bootstrap = {
            "hs": np.empty(spec.bootstrap_draws),
            "fidelity": np.empty(spec.bootstrap_draws),
        }
        for draw in range(spec.bootstrap_draws):
            sampled_left = left_rows[
                rng.integers(0, len(left_rows), size=len(left_rows))
            ]
            sampled_right = right_rows[
                rng.integers(0, len(right_rows), size=len(right_rows))
            ]
            draw_metrics = _set_metrics(
                sampled_left,
                sampled_right,
                rank=spec.rank,
                weights=weights,
            )
            for metric in bootstrap:
                bootstrap[metric][draw] = draw_metrics[metric]
        for metric in ("hs", "fidelity"):
            null_by_cell[(split, metric)] = null[metric]
            block_null_by_cell[(split, metric)] = block_null[metric]
            bootstrap_by_cell[(split, metric)] = bootstrap[metric]
            rows.append(
                {
                    "split": split,
                    "metric": metric,
                    "rank": spec.rank,
                    "observed": metrics[metric],
                    "haar_mean": float(null[metric].mean()),
                    "observed_minus_haar": (
                        metrics[metric] - float(null[metric].mean())
                    ),
                    "bootstrap_lcb_delta": float(
                        np.quantile(
                            bootstrap[metric] - float(null[metric].mean()),
                            0.025,
                        )
                    ),
                    "raw_haar_p": float(
                        (1 + np.sum(null[metric] >= metrics[metric]))
                        / (len(null[metric]) + 1)
                    ),
                    "block_haar_mean": float(block_null[metric].mean()),
                    "observed_minus_block_haar": (
                        metrics[metric] - float(block_null[metric].mean())
                    ),
                    "bootstrap_lcb_block_delta": float(
                        np.quantile(
                            bootstrap[metric]
                            - float(block_null[metric].mean()),
                            0.025,
                        )
                    ),
                    "raw_block_haar_p": float(
                        (1 + np.sum(block_null[metric] >= metrics[metric]))
                        / (len(block_null[metric]) + 1)
                    ),
                }
            )
    cells = pd.DataFrame(rows)
    standardized = []
    observed_z = []
    keys = []
    for _, row in cells.iterrows():
        key = (str(row["split"]), str(row["metric"]))
        null = null_by_cell[key]
        standard = max(float(null.std(ddof=1)), 1e-12)
        standardized.append((null - null.mean()) / standard)
        observed_z.append((float(row["observed"]) - null.mean()) / standard)
        keys.append(key)
    maxima = np.max(np.vstack(standardized), axis=0)
    max_p = {
        key: float((1 + np.sum(maxima >= value)) / (len(maxima) + 1))
        for key, value in zip(keys, observed_z)
    }
    cells["max_haar_p"] = [
        max_p[(str(row["split"]), str(row["metric"]))]
        for _, row in cells.iterrows()
    ]
    block_standardized = []
    block_observed_z = []
    for _, row in cells.iterrows():
        key = (str(row["split"]), str(row["metric"]))
        null = block_null_by_cell[key]
        standard = max(float(null.std(ddof=1)), 1e-12)
        block_standardized.append((null - null.mean()) / standard)
        block_observed_z.append(
            (float(row["observed"]) - null.mean()) / standard
        )
    block_maxima = np.max(np.vstack(block_standardized), axis=0)
    cells["max_block_haar_p"] = [
        float(
            (1 + np.sum(block_maxima >= value))
            / (len(block_maxima) + 1)
        )
        for value in block_observed_z
    ]
    if (
        cells["observed_minus_block_haar"].gt(0).all()
        and cells["bootstrap_lcb_block_delta"].gt(0).all()
        and cells["max_block_haar_p"].le(0.05).all()
    ):
        status = "CROSS_CORPUS_SET_GEOMETRY_OVERLAP_DETECTED"
    else:
        status = "CROSS_CORPUS_SET_GEOMETRY_OVERLAP_NOT_DETECTED"
    return {"status": status, "cells": cells}
