#!/usr/bin/env python3
"""Run the PANDORA-versus-Essays shared-gauge spectral-order replay."""
from __future__ import annotations

import argparse
from dataclasses import replace
from datetime import UTC, datetime
import json
from pathlib import Path
import sys
from typing import Any

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.run_suica_v8_realtext_relation_field import (  # noqa: E402
    load_essays_events,
    load_pandora_events,
)
from suica_core.v8_realtext_relation_field import (  # noqa: E402
    FAMILY_NAMES,
    RealTextRelationSpec,
    build_feature_panel,
)
from suica_core.v8_spectral_order_replay import (  # noqa: E402
    SpectralOrderSpec,
    evaluate_spectral_order_replay,
)
from suica_core.v8_support_containment import _split_raw  # noqa: E402


DEFAULT_CONFIG = ROOT / "configs" / "v8_spectral_order_replay.json"
DEFAULT_OUTPUT = ROOT / "results" / "v8_spectral_order_replay" / "replay_20260809"
DEFAULT_REPORT = ROOT / "reports" / "V8_SPECTRAL_ORDER_REPLAY.md"


def _json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _resolve(path: str | Path) -> Path:
    value = Path(path).expanduser()
    return value if value.is_absolute() else (ROOT / value).resolve()


def _report(
    decision: dict[str, Any],
    schemas: list[dict[str, Any]],
    summaries: pd.DataFrame,
    boundary: str,
) -> str:
    return (
        "# V8 Shared-Gauge Spectral-Order Replay\n\n"
        f"Status: `{decision['status']}`\n\n"
        "This is a post-hoc replay of two directional hypotheses generated by "
        "the preceding corpus-local resolution experiment. PANDORA and Essays "
        "use the same robust diagonal gauge, equal author counts, and exactly "
        "eight events per author. The q=1 Lorenz-excess curve is primary; "
        "q<1 signatures are consistency diagnostics.\n\n"
        "## Data roles\n\n"
        f"{pd.DataFrame(schemas).to_markdown(index=False)}\n\n"
        "## Results\n\n"
        f"{summaries.to_markdown(index=False)}\n\n"
        "## Interpretation\n\n"
        "A supported replay rejects corpus-local scaling and unequal stage "
        "sample size as sufficient explanations of the observed direction. "
        "It does not provide fresh confirmation because the direction was "
        "chosen after inspecting the earlier D1/D2 result. It measures "
        "spectral concentration, not overlap of eigen-directions.\n\n"
        "## Claim boundary\n\n"
        f"{boundary}\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--quick", action="store_true")
    args = parser.parse_args()

    config = _json(args.config)
    base = _json(_resolve(config["base_config"]))
    feature_spec = RealTextRelationSpec(**base["spec"])
    spec = SpectralOrderSpec(
        **{
            **config["spec"],
            "sharpness": tuple(config["spec"]["sharpness"]),
        }
    )
    events_per_author = int(config["matched_events_per_author"])
    base["data"]["pandora"]["minimum_events"] = events_per_author
    base["data"]["pandora"]["maximum_events"] = events_per_author
    base["data"]["essays"]["chunks"] = events_per_author
    if args.quick:
        feature_spec = replace(
            feature_spec,
            transition_null_draws=min(4, feature_spec.transition_null_draws),
        )
        spec = replace(spec, bootstrap_draws=19, minimum_authors=20)
        base["data"]["pandora"]["maximum_authors_per_context"] = min(
            96,
            int(base["data"]["pandora"]["maximum_authors_per_context"]),
        )
        base["data"]["essays"]["maximum_authors"] = min(
            320,
            int(base["data"]["essays"]["maximum_authors"]),
        )

    panels = {}
    schemas = []
    for corpus, loader in (
        ("pandora", load_pandora_events),
        ("essays", load_essays_events),
    ):
        events, schema = loader(base["data"][corpus])
        panel = build_feature_panel(
            events,
            corpus=corpus,
            context_role=schema["context_role"],
            replicate_type=schema["replicate_type"],
            spec=feature_spec,
        )
        schema["split_counts"] = panel.metadata["split"].value_counts().to_dict()
        schemas.append(schema)
        panels[corpus] = panel

    summaries = []
    curves = []
    soft = []
    for family in FAMILY_NAMES:
        raw = {
            corpus: {
                split: _split_raw(panel, family, split)
                for split in ("D0", "D1", "D2")
            }
            for corpus, panel in panels.items()
        }
        result = evaluate_spectral_order_replay(
            family,
            raw["pandora"],
            raw["essays"],
            direction=config["directions"][family],
            left_name="pandora",
            right_name="essays",
            spec=spec,
        )
        summary = {
            key: value
            for key, value in result.items()
            if key not in {"curves", "soft_signature", "d1", "d2"}
        }
        for split in ("d1", "d2"):
            for key, value in result.get(split, {}).items():
                summary[f"{split}_{key}"] = value
        summaries.append(summary)
        if "curves" in result:
            curves.append(result["curves"])
            soft.append(result["soft_signature"])

    summary_frame = pd.DataFrame(summaries)
    supported = summary_frame["status"].eq(
        "SHARED_GAUGE_SPECTRAL_ORDER_REPLAY_SUPPORTED"
    )
    if supported.all():
        status = "SHARED_GAUGE_SPECTRAL_ORDER_REPLAY_SUPPORTED"
    elif supported.any():
        status = "SHARED_GAUGE_SPECTRAL_ORDER_REPLAY_PARTIAL"
    else:
        status = "SHARED_GAUGE_SPECTRAL_ORDER_REPLAY_NOT_SUPPORTED"
    decision = {
        "status": status,
        "version": config["version"],
        "timestamp_utc": datetime.now(UTC).isoformat(),
        "family_status": summary_frame[
            ["family", "status", "direction"]
        ].to_dict(orient="records"),
        "claim_boundary": config["claim_boundary"],
    }

    args.output_dir.mkdir(parents=True, exist_ok=True)
    pd.concat(curves, ignore_index=True).to_csv(
        args.output_dir / "lorenz_curves.csv",
        index=False,
    )
    pd.concat(soft, ignore_index=True).to_csv(
        args.output_dir / "soft_resolution_signature.csv",
        index=False,
    )
    summary_frame.to_csv(args.output_dir / "family_summary.csv", index=False)
    (args.output_dir / "data_schema.json").write_text(
        json.dumps(schemas, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    (args.output_dir / "decision.json").write_text(
        json.dumps(decision, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    report = _report(
        decision,
        schemas,
        summary_frame,
        config["claim_boundary"],
    )
    (args.output_dir / "REPORT.md").write_text(report, encoding="utf-8")
    args.report.write_text(report, encoding="utf-8")
    print(json.dumps(decision, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
