#!/usr/bin/env python3
"""M4-D Leg 6: does orthogonal excitation move the D floor?

EXPLORATORY (open-exploration phase, operator directive 2026-08-01; design and
leans registered in docs/SUICA_M4_D_CURVATURE_AND_RELATION_BRIDGE_PLAN.md,
"Leg 6 -- does excitation move the D floor?", 2026-08-02, commit 14441f6,
before this run). All floor machinery is IMPORTED from
scripts/run_suica_m4_d_dleg_floor_leg4.py (the validated 4b protocol:
oracle-forced route, e_d_paired, budget grid), the two-stage construction from
scripts/run_suica_m4_d_two_stage_leg5.py, and the excitation generator from
suica_core/m4_opportunity_excitation.py (C3.3's frozen balanced signed probes
{+e1,-e1,+e2,-e2} at one reference response SD, injected into the response
state inside the path generator; creation outcomes and downstream paths
regenerated by the same planted mechanism; evaluation stays natural). Nothing
in those modules is reimplemented.

FLOOR ARMS -- {passive, orthogonal excitation} x budget {1x, 2x, 4x} under the
exact Leg-4b protocol (oracle-forced route per author-view, frozen at the 1x
NATURAL oracle stack's V2-selected model on BOTH arms; chart and bases frozen
at V2 1x; per-world author-level medians).

- PASSIVE arm: recomputed bit-exactly via leg4._budget_rows_for_world_rep at
  budgets {1, 2, 4} and ASSERTED per world-rep against Leg 4's persisted
  results/m4_d_dleg_floor/dleg_budget_rows.csv (<= 1e-9 on every error metric,
  flags/routes exactly equal) BEFORE the excitation arm runs on that
  world-rep. No resampling: the excitation pipeline does not force passive
  regeneration (see the pairing note below), so Leg 4b's persisted floor IS
  the passive floor here.
- EXCITATION arm: for each budget b, the natural world at b is regenerated
  under Leg 4b's frozen-world semantics (oracle basis + author parameters
  asserted bit-identical), then build_excited_observed(observed_b, truth_b,
  spec_b, seed=WORLD_SEED, amplitude=1.0) replaces the calibration/selection
  paths with C3.3-excited regenerations (evaluation natural, unused here).
  D_disc(b) and D_orc(b) are refit from the SAME excited panels at the forced
  route; e_d_paired/e_d_true/e_orc_true/e_d_frozen exactly as in Leg 4b.
  Response scale is estimated per budget from the natural panels at that
  budget (C3.3 semantics: the scale of the natural process being replaced);
  the realized scales are persisted.
- PAIRING NOTE (verified at startup and per world at rep 0): the excitation
  generator re-seeds the identical per-panel RNG streams the natural
  generator uses (seed + view*10_000_019 + role*1_000_003) and draws no
  additional randoms, so at amplitude 0 it reproduces the natural
  calibration/selection panels VALUE-EXACTLY (asserted on all fields). The
  excitation arm is therefore a paired realization of the passive arm --
  same noise streams, probe-only causal delta -- not a resample.

STACKING ARM (1x, full 5-world x 8-rep battery) -- two-stage + excitation:
the Leg-5 construction consuming the SAME 1x excited calibration/selection
panels (evaluation natural): excited V2 base stacks (leg3._fit_v2_stack),
stage 1 = leg4._arm2_stacks_for_lambda at the Leg-5 stage-1 ridge
lambda=.125, stage 2 = leg5._two_stage_stack (unpenalized refit at the
stage-1-selected route, base-stack reuse rule intact) -- all on the excited
context. Loop transport and geometries are computed against the NATURAL
oracle stacks (C3.3's fixed maximum-passive oracle endpoint), so the pooled
number is directly comparable to Leg 5's persisted .7605 (same oracle
reference, same natural evaluation; only the discovered side's
calibration/selection data changed). Companions persisted at no extra fitting
cost: arm0_excited (excited V2 baseline) and stage1_excited (excited
penalized stage 1) -- leans bind ONLY on two_stage_excited.

REGISTERED LEANS (adjudication statistics pre-coded here):
- (a) excitation lowers the pooled floor by >= .05 absolute at matched
  budget: pooled e_d_paired floor (mean of pooled medians at {2x, 4x},
  Leg 4b's floor statement, passive .3902) <= .34 under excitation.
- (b) record WHICH scaling reading holds for the excitation arm's pooled
  e_d_paired tail slope over {1x, 2x, 4x} (Leg 4b's tail definition):
  (b1) LEVEL SHIFT, tail stays flat: |slope| < .15;
  (b2) RESTORED BUDGET SCALING: slope <= -.35;
  otherwise INTERMEDIATE (recorded honestly; passive persisted tail -.0512).
- (c) two_stage_excited pooled loop geometry >= .78 (beyond Leg 5's .7605)
  AND the gain is concentrated in the two floor-pinned worlds: mean
  per-world gain over {endogenous_source_partition_matched .6527,
  selection_creation_compensation .6209} exceeds the mean gain over the
  other three worlds (gains vs Leg 5's persisted per-world two_stage values).
PIVOT-IF (registered): pooled floor improvement < .02 under excitation ->
the C3.3 information limit extends to the OBJECT level (excitation buys
Fisher information but not D-resolution); the design lever must be
paired/interventional OCCASIONS (next registered leg). Fires on
(passive_floor - excitation_floor) < .02, i.e. also when excitation worsens
the floor.

Chunked execution (this arc's battery-then-stall workaround): --chunk-start/
--chunk-stop run repetition ranges in the foreground writing partial CSVs;
--assemble concatenates all partials, REFUSES missing or duplicate cells,
and adjudicates from the concatenated rows only.
"""
from __future__ import annotations

import argparse
import glob
import json
import sys
import time
from dataclasses import replace
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
SCRIPTS = ROOT / "scripts"
if str(SCRIPTS) not in sys.path:
    sys.path.insert(0, str(SCRIPTS))

import run_suica_m4_d_dleg_floor_leg4 as leg4  # noqa: E402  bit-exact reuse
import run_suica_m4_d_overspan_control_leg3 as leg3  # noqa: E402
import run_suica_m4_d_two_stage_leg5 as leg5  # noqa: E402

from suica_core.m4_chart_ecology_estimator import (  # noqa: E402
    _flatten_events,
)
from suica_core.m4_chart_ecology_generator import (  # noqa: E402
    M4ChartEcologySpec,
    generate_m4_chart_ecology_world,
)
from suica_core.m4_opportunity_excitation import (  # noqa: E402
    balanced_response_probe,
    build_excited_observed,
)

LOOP_WORLDS = leg3.LOOP_WORLDS
BUDGETS = (1.0, 2.0, 4.0)
AMPLITUDE = 1.0  # C3.3's frozen excitation_amplitude
STAGE1_LAMBDA = leg5.STAGE1_LAMBDA  # 0.125
STACKING_ARMS = ("arm0_excited", "stage1_excited", "two_stage_excited")
ROW_TOLERANCE = 1e-9
FLOOR_METRICS = (
    "e_d_paired",
    "e_d_frozen",
    "e_d_true",
    "e_orc_true",
    "orc_self_drift",
    "reference_gap",
)
LEAN_A_BAR = 0.34
PIVOT_BAR = 0.02
B1_FLAT_BAR = 0.15
B2_SCALING_BAR = -0.35
LEAN_C_POOLED_BAR = 0.78
PINNED_WORLDS = (
    "endogenous_source_partition_matched",
    "selection_creation_compensation",
)


# ---------------------------------------------------------------------------
# persisted references (refused if absent -- registered comparators)
# ---------------------------------------------------------------------------


def _load_leg4_reference() -> tuple[pd.DataFrame, dict[str, Any]]:
    rows_path = ROOT / "results" / "m4_d_dleg_floor" / "dleg_budget_rows.csv"
    decision_path = ROOT / "results" / "m4_d_dleg_floor" / "decision.json"
    if not rows_path.exists() or not decision_path.exists():
        raise RuntimeError(
            "Leg 4 persisted floor artifacts are required references and "
            f"were not found: {rows_path} / {decision_path}"
        )
    stored = pd.read_csv(rows_path)
    stored = stored[stored["budget"].isin(BUDGETS)].copy()
    with decision_path.open("r", encoding="utf-8") as handle:
        decision = json.load(handle)
    pooled = decision["part_4b"]["scaling"]["POOLED"]["e_d_paired"]
    floor = float(pooled["floor_mean_2x_4x"])
    if abs(floor - 0.39) > 0.005:
        raise RuntimeError(
            f"Leg 4 persisted pooled floor {floor:.4f} is not the registered "
            "~.39 comparator; reference battery is not the one registered"
        )
    return stored, decision


def _load_leg5_reference() -> dict[str, Any]:
    path = ROOT / "results" / "m4_d_two_stage" / "decision.json"
    if not path.exists():
        raise RuntimeError(
            "Leg 5 persisted decision is a required reference and was not "
            f"found: {path}"
        )
    with path.open("r", encoding="utf-8") as handle:
        decision = json.load(handle)
    two = decision["arms"]["two_stage"]
    if abs(float(two["pooled_loop_geometry"]) - 0.7605) > 0.005:
        raise RuntimeError(
            "Leg 5 persisted two_stage pooled geometry "
            f"{two['pooled_loop_geometry']:.4f} is not the registered ~.7605 "
            "comparator; reference battery is not the one registered"
        )
    return two


# ---------------------------------------------------------------------------
# startup gate -- probe design sanity (mirrors C3.3's frozen test)
# ---------------------------------------------------------------------------


def _probe_design_gate() -> dict[str, float]:
    probes = np.stack(
        [balanced_response_probe(index, np.ones(2)) for index in range(4)]
    )
    mean_abs = float(np.max(np.abs(np.mean(probes, axis=0))))
    gram_gap = float(np.max(np.abs(probes.T @ probes - 2.0 * np.eye(2))))
    if mean_abs > 1e-12 or gram_gap > 1e-12:
        raise RuntimeError(
            f"balanced probe design gate failed: mean_abs={mean_abs:.3e} "
            f"gram_gap={gram_gap:.3e}"
        )
    return {"probe_mean_abs": mean_abs, "probe_gram_gap": gram_gap}


# ---------------------------------------------------------------------------
# passive-arm reproduction assert vs Leg 4 persisted rows
# ---------------------------------------------------------------------------


def _assert_passive_rows(
    rows: list[dict[str, Any]],
    stored: pd.DataFrame,
    world: str,
    repetition: int,
) -> dict[str, Any]:
    mine = pd.DataFrame(rows)
    reference = stored[
        (stored["world"] == world) & (stored["repetition"] == repetition)
    ]
    keys = ["world", "repetition", "author", "view", "budget"]
    merged = reference.merge(mine, on=keys, suffixes=("_leg4", "_leg6"))
    if len(merged) != len(mine) or len(merged) != len(reference):
        raise RuntimeError(
            f"passive rows misaligned with Leg 4 on {world} rep "
            f"{repetition}: {len(merged)} matches vs mine {len(mine)} / "
            f"stored {len(reference)}"
        )
    checks: dict[str, Any] = {
        "world": world,
        "repetition": repetition,
        "rows_compared": int(len(merged)),
    }
    flags_equal = bool(
        (
            merged["degenerate_reference_leg4"]
            == merged["degenerate_reference_leg6"]
        ).all()
        and (merged["forced_route_leg4"] == merged["forced_route_leg6"]).all()
        and (merged["events_leg4"] == merged["events_leg6"]).all()
    )
    checks["flags_equal"] = flags_equal
    usable = merged[~merged["degenerate_reference_leg4"]]
    max_diff = 0.0
    for name in FLOOR_METRICS:
        diff = float(
            np.max(np.abs(usable[f"{name}_leg4"] - usable[f"{name}_leg6"]))
        )
        checks[f"max_abs_{name}_difference"] = diff
        max_diff = max(max_diff, diff)
    checks["max_abs_difference"] = max_diff
    if max_diff > ROW_TOLERANCE or not flags_equal:
        raise RuntimeError(
            f"passive floor replay diverges from Leg 4 persisted rows on "
            f"{world} rep {repetition}: max|diff|={max_diff:.3e} "
            f"flags_equal={flags_equal}"
        )
    return checks


# ---------------------------------------------------------------------------
# amplitude-0 pipeline identity gate (per world at repetition 0)
# ---------------------------------------------------------------------------

_PANEL_FIELDS = (
    "response",
    "menu",
    "generated_menu",
    "external_menu",
    "choice",
    "history",
    "duration",
    "environment",
)


def _amplitude0_identity_gate(
    context: dict[str, Any],
    spec: M4ChartEcologySpec,
) -> dict[str, Any]:
    excited0 = build_excited_observed(
        context["observed"],
        context["truth"],
        spec,
        seed=context["seed"],
        amplitude=0.0,
    )
    mismatches = []
    for view in ("train", "test"):
        for role in ("calibration", "selection"):
            natural = getattr(context["observed"].ecology, f"{view}_{role}")
            rebuilt = getattr(excited0.ecology, f"{view}_{role}")
            for field in _PANEL_FIELDS:
                if not np.array_equal(
                    getattr(natural, field), getattr(rebuilt, field)
                ):
                    mismatches.append(f"{view}_{role}.{field}")
    if mismatches:
        raise RuntimeError(
            "amplitude-0 pipeline identity gate FAILED on "
            f"{context['world']} rep {context['repetition']}: the excitation "
            "generator does not reproduce the natural panels on the same "
            f"RNG streams; mismatched fields: {mismatches}"
        )
    return {
        "world": context["world"],
        "repetition": context["repetition"],
        "fields_checked": len(_PANEL_FIELDS) * 4,
        "identity_holds": True,
    }


# ---------------------------------------------------------------------------
# excitation floor arm (Leg-4b protocol on excited panels)
# ---------------------------------------------------------------------------


def _excited_budget_rows_for_world_rep(
    context: dict[str, Any],
    *,
    spec: M4ChartEcologySpec,
    budgets: tuple[float, ...],
    excited_1x: Any,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Leg-4b budget rows with C3.3-excited calibration/selection panels.

    Mirrors leg4._budget_rows_for_world_rep row-for-row (same forced routes,
    same references, same degenerate rule) with the panels swapped for
    build_excited_observed output at each budget. The 1x excited observed is
    passed in so the stacking arm consumes the identical object.
    """
    world = context["world"]
    repetition = context["repetition"]
    seed = context["seed"]
    truth = context["truth"]
    v2_basis = context["v2_basis"]
    oracle_basis = truth.oracle_basis
    hazard_ridge = context["fit_kwargs"]["hazard_ridge"]
    iterations = context["fit_kwargs"]["logistic_iterations"]
    dimensions = context["flat"][("train", 0)][0]["response_next"].shape[1]
    true_d = {
        author: leg4._true_derivative(truth, author)
        for author in range(context["authors"])
    }
    rows: list[dict[str, Any]] = []
    scales: list[dict[str, Any]] = []
    for budget in budgets:
        events_b = int(round(spec.events * budget))
        if budget == 1.0:
            excited_b = excited_1x
            spec_b = spec
        else:
            spec_b = replace(spec, events=events_b)
            observed_b, truth_b = generate_m4_chart_ecology_world(
                world=world,
                spec=spec_b,
                seed=seed,
            )
            for role in ("calibration", "selection", "evaluation"):
                if not np.array_equal(
                    truth_b.oracle_basis[role], oracle_basis[role]
                ):
                    raise RuntimeError(
                        f"frozen-world violation at budget {budget}: oracle "
                        f"basis[{role}] changed on {world} rep {repetition}"
                    )
            for name in ("creation", "gate", "generated_base", "selection"):
                if not np.array_equal(
                    truth_b.author_parameters[name],
                    truth.author_parameters[name],
                ):
                    raise RuntimeError(
                        f"frozen-world violation at budget {budget}: author "
                        f"parameter {name} changed on {world} rep {repetition}"
                    )
            excited_b = build_excited_observed(
                observed_b,
                truth_b,
                spec_b,
                seed=seed,
                amplitude=AMPLITUDE,
            )
        scale = excited_b.ecology.design["response_excitation_scale"]
        scales.append(
            {
                "world": world,
                "repetition": repetition,
                "budget": budget,
                "events": events_b,
                "scale_0": float(scale[0]),
                "scale_1": float(scale[1]),
                "amplitude": AMPLITUDE,
            }
        )
        for view in ("train", "test"):
            calibration_panel = getattr(
                excited_b.ecology, f"{view}_calibration"
            )
            selection_panel = getattr(excited_b.ecology, f"{view}_selection")
            for author in range(context["authors"]):
                oracle_stack = context["oracle_stacks"][view][author]
                forced_route = oracle_stack["selected_model"]
                d_orc_1x = oracle_stack["D"]
                d_norm_orc_1x = float(np.linalg.norm(d_orc_1x))
                keys = {
                    "world": world,
                    "repetition": repetition,
                    "seed": seed,
                    "author": author,
                    "view": view,
                    "budget": budget,
                    "events": events_b,
                    "forced_route": forced_route,
                }
                if d_norm_orc_1x < leg4.FLIP_TOLERANCE:
                    rows.append(
                        {
                            **keys,
                            "degenerate_reference": True,
                            "e_d_paired": np.nan,
                            "e_d_frozen": np.nan,
                            "e_d_true": np.nan,
                            "e_orc_true": np.nan,
                            "orc_self_drift": np.nan,
                            "reference_gap": np.nan,
                            "d_norm_disc_b": np.nan,
                            "d_norm_orc_b": np.nan,
                            "d_norm_orc_1x": d_norm_orc_1x,
                            "d_norm_true": float(
                                np.linalg.norm(true_d[author])
                            ),
                        }
                    )
                    continue
                calibration = _flatten_events(calibration_panel, author)
                selection = _flatten_events(selection_panel, author)
                d_disc = leg4._forced_route_derivative(
                    calibration,
                    selection,
                    v2_basis,
                    model=forced_route,
                    hazard_ridge=hazard_ridge,
                    logistic_iterations=iterations,
                    dimensions=dimensions,
                )
                d_orc = leg4._forced_route_derivative(
                    calibration,
                    selection,
                    oracle_basis,
                    model=forced_route,
                    hazard_ridge=hazard_ridge,
                    logistic_iterations=iterations,
                    dimensions=dimensions,
                )
                d_true = true_d[author]
                rows.append(
                    {
                        **keys,
                        "degenerate_reference": False,
                        "e_d_paired": leg3._relative_error(d_disc, d_orc),
                        "e_d_frozen": leg3._relative_error(d_disc, d_orc_1x),
                        "e_d_true": leg3._relative_error(d_disc, d_true),
                        "e_orc_true": leg3._relative_error(d_orc, d_true),
                        "orc_self_drift": leg3._relative_error(
                            d_orc, d_orc_1x
                        ),
                        "reference_gap": leg3._relative_error(
                            d_orc_1x, d_true
                        ),
                        "d_norm_disc_b": float(np.linalg.norm(d_disc)),
                        "d_norm_orc_b": float(np.linalg.norm(d_orc)),
                        "d_norm_orc_1x": d_norm_orc_1x,
                        "d_norm_true": float(np.linalg.norm(d_true)),
                    }
                )
    return rows, scales


# ---------------------------------------------------------------------------
# stacking arm -- two-stage + excitation at 1x
# ---------------------------------------------------------------------------


def _stacking_rows_for_world_rep(
    context: dict[str, Any],
    excited_1x: Any,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], dict[str, Any]]:
    """arm0_excited / stage1_excited / two_stage_excited vs natural oracle."""
    keys_base = {
        "world": context["world"],
        "repetition": context["repetition"],
        "seed": context["seed"],
    }
    exc_flat: dict[tuple[str, int], tuple[dict, dict, dict]] = {}
    exc_base: dict[str, list[dict[str, Any]]] = {"train": [], "test": []}
    for view in ("train", "test"):
        calibration_panel = getattr(excited_1x.ecology, f"{view}_calibration")
        selection_panel = getattr(excited_1x.ecology, f"{view}_selection")
        for author in range(context["authors"]):
            natural_eval = context["flat"][(view, author)][2]
            events = (
                _flatten_events(calibration_panel, author),
                _flatten_events(selection_panel, author),
                natural_eval,
            )
            exc_flat[(view, author)] = events
            exc_base[view].append(
                leg3._fit_v2_stack(
                    *events,
                    context["v2_basis"],
                    **context["fit_kwargs"],
                    query_masks=context["query_masks"],
                )
            )
    exc_context = {**context, "base_stacks": exc_base, "flat": exc_flat}
    stage1_stacks = leg4._arm2_stacks_for_lambda(exc_context, STAGE1_LAMBDA)
    two_stage_stacks: dict[str, list[dict[str, Any]]] = {
        "train": [],
        "test": [],
    }
    fresh_refits = 0
    for view in ("train", "test"):
        for author in range(context["authors"]):
            stack, fresh = leg5._two_stage_stack(
                exc_context, view, author, stage1_stacks[view][author]
            )
            two_stage_stacks[view].append(stack)
            if fresh:
                fresh_refits += 1
    arm_stacks = {
        "arm0_excited": exc_base,
        "stage1_excited": stage1_stacks,
        "two_stage_excited": two_stage_stacks,
    }
    loop_rows: list[dict[str, Any]] = []
    world_rows: list[dict[str, Any]] = []
    for arm in STACKING_ARMS:
        arm_rows = [
            leg3._loop_row(
                {**keys_base, "author": author, "view": view},
                arm,
                arm_stacks[arm][view][author],
                context["oracle_stacks"][view][author],
            )
            for view in ("train", "test")
            for author in range(context["authors"])
        ]
        loop_rows.extend(arm_rows)
        geometries = leg3._arm_geometries(
            arm_stacks[arm], context["oracle_stacks"]
        )
        world_rows.append(
            {
                **keys_base,
                "arm": arm,
                "chart_family": context["chart"].selected_family,
                "arm_lambda": (
                    STAGE1_LAMBDA if arm == "stage1_excited" else np.nan
                ),
                **geometries,
                "flips": int(sum(row["model_flip"] for row in arm_rows)),
                "route_mismatches": int(
                    sum(row["route_mismatch"] for row in arm_rows)
                ),
                "mean_e_loop": float(
                    np.mean([row["e_loop"] for row in arm_rows])
                ),
                "mean_e_d": float(
                    np.mean([row["e_d_atom"] for row in arm_rows])
                ),
            }
        )
    structure = {**keys_base, "fresh_stage2_refits": fresh_refits}
    return loop_rows, world_rows, structure


# ---------------------------------------------------------------------------
# chunk execution
# ---------------------------------------------------------------------------


def _run_chunk(
    args: argparse.Namespace,
    config: dict[str, Any],
    spec: M4ChartEcologySpec,
    repetitions: tuple[int, ...],
    worlds: list[str],
) -> None:
    stored_passive, _ = _load_leg4_reference()
    probe_gate = _probe_design_gate()
    world_index = {
        world: index for index, world in enumerate(config["worlds"])
    }
    archived_path = ROOT / "results" / "m4_chart_ecology" / "metrics.csv"
    archived = pd.read_csv(archived_path) if archived_path.exists() else None

    def expected_for(world: str, repetition: int, seed: int):
        if archived is None:
            return None
        match = archived[
            (archived["world"] == world)
            & (archived["repetition"] == repetition)
            & (archived["seed"] == seed)
        ]
        if len(match) != 1:
            return None
        return {
            name: float(match[name].iloc[0])
            for name in (
                "loop_action_geometry",
                "choice_action_geometry",
                "creation_action_geometry",
            )
        }

    floor_rows: list[dict[str, Any]] = []
    scale_rows: list[dict[str, Any]] = []
    stacking_loop_rows: list[dict[str, Any]] = []
    stacking_world_rows: list[dict[str, Any]] = []
    validation_rows: list[dict[str, Any]] = []
    passive_checks: list[dict[str, Any]] = []
    identity_gates: list[dict[str, Any]] = []
    structures: list[dict[str, Any]] = []
    for repetition in repetitions:
        for world in worlds:
            seed = leg3._world_seed(
                int(config["seed"]), repetition, world, world_index[world]
            )
            started = time.time()
            context = leg4._build_context(
                world,
                repetition,
                seed,
                spec=spec,
                config=config,
                expected_geometries=expected_for(world, repetition, seed),
            )
            validation_rows.extend(context["validation_rows"])

            # ---- passive floor: bit-exact Leg-4b reuse + persisted assert
            passive_rows, gates_4b = leg4._budget_rows_for_world_rep(
                context,
                spec=spec,
                budgets=BUDGETS,
            )
            if (
                gates_4b["orc_refit_identity_max_gap_1x"] > ROW_TOLERANCE
                or gates_4b["disc_forced_identity_max_gap_1x"] > ROW_TOLERANCE
            ):
                raise RuntimeError(
                    f"1x identity gate failed on {world} rep {repetition}: "
                    f"{gates_4b}"
                )
            passive_checks.append(
                _assert_passive_rows(
                    passive_rows, stored_passive, world, repetition
                )
            )
            floor_rows.extend(
                {**row, "arm": "passive"} for row in passive_rows
            )

            # ---- amplitude-0 pipeline identity gate (rep 0 per world)
            if repetition == 0:
                identity_gates.append(
                    _amplitude0_identity_gate(context, spec)
                )

            # ---- excitation floor + stacking (shared 1x excited build)
            excited_1x = build_excited_observed(
                context["observed"],
                context["truth"],
                spec,
                seed=seed,
                amplitude=AMPLITUDE,
            )
            excited_rows, scales = _excited_budget_rows_for_world_rep(
                context,
                spec=spec,
                budgets=BUDGETS,
                excited_1x=excited_1x,
            )
            floor_rows.extend(
                {**row, "arm": "excitation"} for row in excited_rows
            )
            scale_rows.extend(scales)

            loop_rows, world_rows, structure = _stacking_rows_for_world_rep(
                context, excited_1x
            )
            stacking_loop_rows.extend(loop_rows)
            stacking_world_rows.extend(world_rows)
            structures.append(structure)

            by_arm = {
                row["arm"]: round(row["loop_action_geometry"], 3)
                for row in world_rows
            }
            print(
                f"[leg6] rep={repetition} world={world} stacking geometry "
                f"{by_arm} passive-assert max "
                f"{passive_checks[-1]['max_abs_difference']:.2e} "
                f"({time.time() - started:.0f}s)",
                flush=True,
            )

    suffix = f"rep{repetitions[0]}-{repetitions[-1]}"
    args.output.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(floor_rows).to_csv(
        args.output / f"partial_floor_budget_rows_{suffix}.csv", index=False
    )
    pd.DataFrame(scale_rows).to_csv(
        args.output / f"partial_excitation_scales_{suffix}.csv", index=False
    )
    pd.DataFrame(stacking_loop_rows).to_csv(
        args.output / f"partial_stacking_per_loop_{suffix}.csv", index=False
    )
    pd.DataFrame(stacking_world_rows).to_csv(
        args.output / f"partial_stacking_world_rep_{suffix}.csv", index=False
    )
    pd.DataFrame(validation_rows).to_csv(
        args.output / f"partial_v2_validation_{suffix}.csv", index=False
    )
    pd.DataFrame(passive_checks).to_csv(
        args.output / f"partial_passive_check_{suffix}.csv", index=False
    )
    gates = {
        "probe_design_gate": probe_gate,
        "amplitude0_identity_gates": identity_gates,
        "stacking_structure": structures,
        "repetitions": list(repetitions),
        "worlds": worlds,
    }
    with (args.output / f"partial_gates_{suffix}.json").open(
        "w", encoding="utf-8"
    ) as handle:
        json.dump(gates, handle, indent=2, sort_keys=True)
        handle.write("\n")
    print(f"[chunk done] {suffix}", flush=True)


# ---------------------------------------------------------------------------
# assembly -- refuse missing/duplicate cells, adjudicate from rows only
# ---------------------------------------------------------------------------


def _concat_partials(output: Path, stem: str) -> pd.DataFrame:
    paths = sorted(glob.glob(str(output / f"partial_{stem}_rep*.csv")))
    if not paths:
        raise RuntimeError(f"no partial CSVs found for {stem} under {output}")
    return pd.concat(
        [pd.read_csv(path) for path in paths], ignore_index=True
    )


def _refuse_bad_cells(
    frame: pd.DataFrame,
    keys: list[str],
    expected: int,
    label: str,
) -> None:
    duplicated = int(frame.duplicated(subset=keys).sum())
    if duplicated:
        raise RuntimeError(f"{label}: {duplicated} duplicate cells refused")
    if len(frame) != expected:
        raise RuntimeError(
            f"{label}: {len(frame)} rows != expected {expected}; missing "
            "cells refused"
        )


def _floor_analysis_for_arm(
    floor_frame: pd.DataFrame, arm: str
) -> tuple[pd.DataFrame, dict[str, Any]]:
    subset = floor_frame[floor_frame["arm"] == arm].drop(columns=["arm"])
    summary, analysis = leg4._scaling_summary(subset)
    summary.insert(0, "arm", arm)
    return summary, analysis


def _assemble(args: argparse.Namespace, config: dict[str, Any]) -> None:
    stored_passive, leg4_decision = _load_leg4_reference()
    leg5_two_stage = _load_leg5_reference()
    repetitions = int(config["repetitions"])
    worlds = list(LOOP_WORLDS)
    n_world_reps = len(worlds) * repetitions
    authors = 16
    n_rows_per_arm = n_world_reps * len(BUDGETS) * 2 * authors

    floor_frame = _concat_partials(args.output, "floor_budget_rows")
    scales = _concat_partials(args.output, "excitation_scales")
    stacking_loops = _concat_partials(args.output, "stacking_per_loop")
    stacking_worlds = _concat_partials(args.output, "stacking_world_rep")
    validation = _concat_partials(args.output, "v2_validation")
    passive_checks = _concat_partials(args.output, "passive_check")
    gate_paths = sorted(
        glob.glob(str(args.output / "partial_gates_rep*.json"))
    )
    gates = []
    for path in gate_paths:
        with open(path, "r", encoding="utf-8") as handle:
            gates.append(json.load(handle))

    _refuse_bad_cells(
        floor_frame,
        ["arm", "world", "repetition", "author", "view", "budget"],
        2 * n_rows_per_arm,
        "floor rows",
    )
    _refuse_bad_cells(
        scales,
        ["world", "repetition", "budget"],
        n_world_reps * len(BUDGETS),
        "excitation scales",
    )
    _refuse_bad_cells(
        stacking_loops,
        ["arm", "world", "repetition", "author", "view"],
        len(STACKING_ARMS) * n_world_reps * 2 * authors,
        "stacking loop rows",
    )
    _refuse_bad_cells(
        stacking_worlds,
        ["arm", "world", "repetition"],
        len(STACKING_ARMS) * n_world_reps,
        "stacking world-rep rows",
    )
    _refuse_bad_cells(
        passive_checks,
        ["world", "repetition"],
        n_world_reps,
        "passive reproduction checks",
    )
    if not bool(passive_checks["flags_equal"].all()):
        raise RuntimeError("assembled passive checks contain unequal flags")
    passive_max = float(passive_checks["max_abs_difference"].max())
    if passive_max > ROW_TOLERANCE:
        raise RuntimeError(
            f"assembled passive reproduction max diff {passive_max:.3e}"
        )
    identity_gates = [
        gate
        for chunk in gates
        for gate in chunk["amplitude0_identity_gates"]
    ]
    if sorted(gate["world"] for gate in identity_gates) != sorted(worlds):
        raise RuntimeError(
            "amplitude-0 identity gates missing for some world: "
            f"{[gate['world'] for gate in identity_gates]}"
        )

    # ---- floor analysis per arm
    floor_summaries = []
    floor_analysis: dict[str, Any] = {}
    for arm in ("passive", "excitation"):
        summary, analysis = _floor_analysis_for_arm(floor_frame, arm)
        floor_summaries.append(summary)
        floor_analysis[arm] = analysis
    floor_summary_frame = pd.concat(floor_summaries, ignore_index=True)

    # decision-level cross-check: recomputed passive pooled medians vs
    # Leg 4's persisted decision (tail slope + medians at 1/2/4)
    persisted_pooled = leg4_decision["part_4b"]["scaling"]["POOLED"][
        "e_d_paired"
    ]
    recomputed_pooled = floor_analysis["passive"]["POOLED"]["e_d_paired"]
    for budget in BUDGETS:
        gap = abs(
            recomputed_pooled["medians_by_budget"][str(budget)]
            - persisted_pooled["medians_by_budget"][str(budget)]
        )
        if gap > ROW_TOLERANCE:
            raise RuntimeError(
                f"recomputed passive pooled median at {budget}x diverges "
                f"from Leg 4 persisted decision by {gap:.3e}"
            )
    if (
        abs(
            recomputed_pooled["tail_slope"]
            - persisted_pooled["tail_slope"]
        )
        > 1e-6
    ):
        raise RuntimeError(
            "recomputed passive pooled tail slope diverges from Leg 4 "
            f"persisted decision: {recomputed_pooled['tail_slope']} vs "
            f"{persisted_pooled['tail_slope']}"
        )

    passive_floor = float(recomputed_pooled["floor_mean_2x_4x"])
    excitation_pooled = floor_analysis["excitation"]["POOLED"]["e_d_paired"]
    excitation_floor = float(excitation_pooled["floor_mean_2x_4x"])
    floor_improvement = passive_floor - excitation_floor
    matched_budget_deltas = {
        str(budget): float(
            floor_analysis["passive"]["POOLED"]["e_d_paired"][
                "medians_by_budget"
            ][str(budget)]
            - excitation_pooled["medians_by_budget"][str(budget)]
        )
        for budget in BUDGETS
    }
    per_world_floor = {
        world: {
            "passive_floor_mean_2x_4x": float(
                floor_analysis["passive"][world]["e_d_paired"][
                    "floor_mean_2x_4x"
                ]
            ),
            "excitation_floor_mean_2x_4x": float(
                floor_analysis["excitation"][world]["e_d_paired"][
                    "floor_mean_2x_4x"
                ]
            ),
            "improvement": float(
                floor_analysis["passive"][world]["e_d_paired"][
                    "floor_mean_2x_4x"
                ]
                - floor_analysis["excitation"][world]["e_d_paired"][
                    "floor_mean_2x_4x"
                ]
            ),
            "excitation_verdict": floor_analysis["excitation"][world][
                "e_d_paired"
            ]["verdict"],
        }
        for world in worlds
    }

    lean_a_hold = bool(excitation_floor <= LEAN_A_BAR)
    excitation_tail = float(excitation_pooled["tail_slope"])
    if excitation_tail <= B2_SCALING_BAR:
        lean_b_reading = "B2_RESTORED_BUDGET_SCALING"
    elif abs(excitation_tail) < B1_FLAT_BAR:
        lean_b_reading = "B1_LEVEL_SHIFT_FLAT_TAIL"
    else:
        lean_b_reading = "INTERMEDIATE"
    pivot_triggered = bool(floor_improvement < PIVOT_BAR)

    # ---- stacking adjudication
    arm_summaries = {
        arm: leg4._arm_summary(stacking_loops, stacking_worlds, arm)
        for arm in STACKING_ARMS
    }
    two_exc = arm_summaries["two_stage_excited"]
    pooled_exc = float(two_exc["pooled_loop_geometry"])
    leg5_per_world = leg5_two_stage["per_world_loop_geometry"]
    per_world_gain = {
        world: float(
            two_exc["per_world_loop_geometry"][world] - leg5_per_world[world]
        )
        for world in worlds
    }
    pinned_gain = float(
        np.mean([per_world_gain[world] for world in PINNED_WORLDS])
    )
    other_gain = float(
        np.mean(
            [
                per_world_gain[world]
                for world in worlds
                if world not in PINNED_WORLDS
            ]
        )
    )
    lean_c_pooled_hold = bool(pooled_exc >= LEAN_C_POOLED_BAR)
    lean_c_concentration_hold = bool(pinned_gain > other_gain)
    lean_c_hold = bool(lean_c_pooled_hold and lean_c_concentration_hold)

    if pivot_triggered:
        outcome = (
            "PIVOT_C33_INFORMATION_LIMIT_EXTENDS_TO_OBJECT_LEVEL_"
            "NEXT_LEVER_PAIRED_INTERVENTIONAL_OCCASIONS"
        )
    elif lean_a_hold:
        outcome = "EXCITATION_MOVES_THE_OBJECT_LEVEL_FLOOR"
    else:
        outcome = (
            "EXCITATION_MOVES_FLOOR_BELOW_REGISTERED_LEAN_"
            "DESIGN_CHANGE_TRACK_PARTIALLY_LIVE"
        )

    floor_frame = floor_frame.sort_values(
        ["arm", "world", "repetition", "author", "view", "budget"]
    )
    stacking_loops = stacking_loops.sort_values(
        ["arm", "world", "repetition", "author", "view"]
    )
    stacking_worlds = stacking_worlds.sort_values(
        ["arm", "world", "repetition"]
    )
    floor_frame.to_csv(args.output / "floor_budget_rows.csv", index=False)
    floor_summary_frame.to_csv(
        args.output / "floor_scaling_summary.csv", index=False
    )
    scales.sort_values(["world", "repetition", "budget"]).to_csv(
        args.output / "excitation_scales.csv", index=False
    )
    stacking_loops.to_csv(
        args.output / "stacking_per_loop_metrics.csv", index=False
    )
    stacking_worlds.to_csv(
        args.output / "stacking_world_rep_metrics.csv", index=False
    )
    validation.to_csv(args.output / "v2_validation.csv", index=False)
    passive_checks.sort_values(["world", "repetition"]).to_csv(
        args.output / "passive_reproduction_check.csv", index=False
    )

    n_degenerate = {
        arm: int(
            floor_frame[floor_frame["arm"] == arm][
                "degenerate_reference"
            ].sum()
        )
        for arm in ("passive", "excitation")
    }
    scale_summary = {
        str(budget): {
            "mean": [
                float(group["scale_0"].mean()),
                float(group["scale_1"].mean()),
            ],
            "min": [
                float(group["scale_0"].min()),
                float(group["scale_1"].min()),
            ],
            "max": [
                float(group["scale_0"].max()),
                float(group["scale_1"].max()),
            ],
        }
        for budget, group in scales.groupby("budget")
    }
    worsened_worlds = [
        world
        for world in worlds
        if per_world_floor[world]["improvement"] < 0.0
    ]

    decision = {
        "estimand_id": "SUICA_M4_D_LEG6_EXCITATION_FLOOR",
        "tier": "EXPLORATORY",
        "config_seed": int(config["seed"]),
        "outcome": outcome,
        "design": {
            "floor_arms": (
                "{passive, orthogonal excitation} x budget {1x, 2x, 4x} "
                "under the exact Leg-4b protocol: oracle-forced route "
                "(frozen at the 1x NATURAL oracle stack's V2-selected model "
                "on both arms), chart/bases frozen at V2 1x, e_d_paired "
                "primary, author-level medians"
            ),
            "excitation": (
                "C3.3's frozen build_excited_observed as implemented: "
                "balanced zero-mean signed probes {+e1,-e1,+e2,-e2} at "
                f"amplitude {AMPLITUDE} reference response SD injected into "
                "the response state inside the path generator; creation "
                "outcomes and downstream paths regenerated by the same "
                "planted mechanism; evaluation natural; response scale "
                "estimated per budget from the natural panels at that budget"
            ),
            "pairing": (
                "excited panels ride the identical per-panel RNG streams as "
                "the natural panels (same seeds, no additional draws): at "
                "amplitude 0 the pipeline reproduces the natural "
                "calibration/selection panels value-exactly (gated per "
                "world at rep 0); the excitation arm is a paired "
                "realization, not a resample -- no passive regeneration "
                "was needed"
            ),
            "stacking_arm": (
                "two-stage (Leg 5 construction: stage 1 penalized route "
                f"selection at lambda={STAGE1_LAMBDA}, stage 2 unpenalized "
                "refit at the stage-1 route) consuming the SAME 1x excited "
                "calibration/selection panels; loop transport vs the "
                "NATURAL oracle stacks (C3.3's maximum-passive oracle "
                "endpoint) so the pooled number is directly comparable to "
                "Leg 5's persisted .7605; companions arm0_excited and "
                "stage1_excited persisted, leans bind on two_stage_excited "
                "only"
            ),
            "budgets": list(BUDGETS),
            "amplitude": AMPLITUDE,
        },
        "faithfulness": {
            "passive_reproduction": {
                "reference": "results/m4_d_dleg_floor/dleg_budget_rows.csv",
                "world_reps_checked": int(len(passive_checks)),
                "rows_compared": int(passive_checks["rows_compared"].sum()),
                "max_abs_difference": passive_max,
                "all_flags_equal": bool(
                    passive_checks["flags_equal"].all()
                ),
            },
            "passive_decision_crosscheck": {
                "pooled_medians_match_leg4_decision": True,
                "tail_slope_recomputed": float(
                    recomputed_pooled["tail_slope"]
                ),
                "tail_slope_persisted": float(
                    persisted_pooled["tail_slope"]
                ),
            },
            "amplitude0_identity_gates": identity_gates,
            "probe_design_gate": gates[0]["probe_design_gate"],
            "v2_validation_max_abs_difference": (
                float(validation["abs_difference"].max())
                if len(validation)
                else float("nan")
            ),
        },
        "floor": {
            "pooled": {
                "passive_medians_by_budget": recomputed_pooled[
                    "medians_by_budget"
                ],
                "excitation_medians_by_budget": excitation_pooled[
                    "medians_by_budget"
                ],
                "matched_budget_deltas": matched_budget_deltas,
                "passive_floor_mean_2x_4x": passive_floor,
                "excitation_floor_mean_2x_4x": excitation_floor,
                "floor_improvement": floor_improvement,
                "passive_tail_slope": float(recomputed_pooled["tail_slope"]),
                "excitation_tail_slope": excitation_tail,
                "excitation_overall_slope_1x_4x": float(
                    excitation_pooled["overall_slope"]
                ),
                "excitation_verdict": excitation_pooled["verdict"],
            },
            "per_world": per_world_floor,
            "scaling_analysis": floor_analysis,
            "degenerate_reference_rows": n_degenerate,
            "excitation_scale_summary": scale_summary,
        },
        "stacking": {
            "arms": arm_summaries,
            "leg5_two_stage_persisted": {
                "pooled_loop_geometry": float(
                    leg5_two_stage["pooled_loop_geometry"]
                ),
                "per_world_loop_geometry": leg5_per_world,
                "flips_total": int(leg5_two_stage["flips_total"]),
                "median_e_d": float(leg5_two_stage["median_e_d"]),
                "source": "results/m4_d_two_stage/decision.json",
            },
            "two_stage_excited_vs_leg5": {
                "pooled_gain": float(
                    pooled_exc
                    - float(leg5_two_stage["pooled_loop_geometry"])
                ),
                "per_world_gain": per_world_gain,
                "pinned_worlds": list(PINNED_WORLDS),
                "mean_gain_pinned": pinned_gain,
                "mean_gain_other": other_gain,
            },
            "fresh_stage2_refits_total": int(
                sum(
                    structure["fresh_stage2_refits"]
                    for chunk in gates
                    for structure in chunk["stacking_structure"]
                )
            ),
        },
        "lean_a": {
            "registered": (
                "excitation lowers the pooled floor by >= .05 absolute at "
                "matched budget: pooled e_d_paired floor (mean of pooled "
                "medians at {2x,4x}; passive .3902) <= .34"
            ),
            "value": excitation_floor,
            "passive_reference": passive_floor,
            "hold": lean_a_hold,
        },
        "lean_b": {
            "registered": (
                "record WHICH scaling reading holds for the excitation "
                "arm's pooled e_d_paired tail slope over {1x,2x,4x}: "
                "(b1) level shift with flat tail |slope| < .15 vs "
                "(b2) restored budget scaling slope <= -.35"
            ),
            "excitation_tail_slope": excitation_tail,
            "passive_tail_slope": float(recomputed_pooled["tail_slope"]),
            "reading": lean_b_reading,
        },
        "lean_c": {
            "registered": (
                "two-stage+excitation pooled loop geometry >= .78 (beyond "
                "Leg 5's .7605) with the gain concentrated in the two "
                "floor-pinned worlds (partition .6527, compensation .6209): "
                "mean pinned-world gain > mean other-world gain"
            ),
            "pooled_value": pooled_exc,
            "pooled_bar_hold": lean_c_pooled_hold,
            "concentration_hold": lean_c_concentration_hold,
            "hold": lean_c_hold,
        },
        "pivot_if": {
            "registered": (
                "pooled floor moves < .02 under excitation -> the C3.3 "
                "information limit extends to the OBJECT level (excitation "
                "buys Fisher information but not D-resolution); the design "
                "lever must be paired/interventional OCCASIONS (next "
                "registered leg)"
            ),
            "floor_improvement": floor_improvement,
            "triggered": pivot_triggered,
            "declaration": (
                "C33_INFORMATION_LIMIT_EXTENDS_TO_OBJECT_LEVEL_"
                "NEXT_LEVER_PAIRED_INTERVENTIONAL_OCCASIONS"
                if pivot_triggered
                else "not triggered"
            ),
        },
        "anomalies": {
            "stage1_excited_flips_vs_natural_73": int(
                arm_summaries["stage1_excited"]["flips_total"]
            ),
            "arm0_excited_flips_vs_natural_196": int(
                arm_summaries["arm0_excited"]["flips_total"]
            ),
            "worlds_where_excitation_worsens_floor": worsened_worlds,
            "excitation_scale_drift_across_budgets": scale_summary,
        },
        "claim_boundary": (
            "Finite synthetic M4-C.2 worlds only; truth-referenced "
            "estimator diagnostics (oracle-basis fits, oracle-forced "
            "routes, and generator-law derivatives are consumed as "
            "references), so nothing here is an operational rescue of "
            "chart transport or a reopened gate; the V1/V2 and C3.3 NO-GO "
            "decisions stand; excitation is a designed creation-input "
            "intervention available only because the generator is known -- "
            "no natural-text, personality, emotion, or clinical claim; "
            "EXPLORATORY tier under the 2026-08-01 open-exploration "
            "directive."
        ),
    }
    with (args.output / "decision.json").open("w", encoding="utf-8") as f:
        json.dump(decision, f, indent=2, sort_keys=True)
        f.write("\n")
    print(json.dumps(decision["floor"]["pooled"], indent=2, sort_keys=True))
    print(
        json.dumps(
            {
                "outcome": outcome,
                "lean_a_hold": lean_a_hold,
                "lean_b_reading": lean_b_reading,
                "lean_c_hold": lean_c_hold,
                "pivot_triggered": pivot_triggered,
                "pooled_stacking": pooled_exc,
            },
            indent=2,
            sort_keys=True,
        )
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--config",
        type=Path,
        default=ROOT / "configs" / "m4_chart_ecology.json",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "results" / "m4_d_excitation_floor",
    )
    parser.add_argument("--chunk-start", type=int, default=None)
    parser.add_argument("--chunk-stop", type=int, default=None)
    parser.add_argument("--assemble", action="store_true")
    parser.add_argument("--smoke", action="store_true")
    args = parser.parse_args()

    started = time.time()
    config = leg3._load(args.config)
    spec = M4ChartEcologySpec(**config["base_spec"])

    if args.smoke:
        args.output = ROOT / "results" / "_smoke_m4_d_excitation_floor"
        worlds = list(LOOP_WORLDS)[:2]
        _run_chunk(args, config, spec, (0,), worlds)
        print(
            f"[smoke done] partials under {args.output} "
            f"({time.time() - started:.0f}s)",
            flush=True,
        )
        return
    if args.assemble:
        _assemble(args, config)
        print(f"[assembled] total {time.time() - started:.0f}s", flush=True)
        return
    if args.chunk_start is None or args.chunk_stop is None:
        raise SystemExit(
            "provide --chunk-start/--chunk-stop for a run chunk, "
            "--assemble to adjudicate, or --smoke"
        )
    repetitions = tuple(range(args.chunk_start, args.chunk_stop))
    _run_chunk(args, config, spec, repetitions, list(LOOP_WORLDS))
    print(f"[done] total {time.time() - started:.0f}s", flush=True)


if __name__ == "__main__":
    main()
