#!/usr/bin/env python3
"""SUICA D1 -- PROSPECTIVE SEAL #2.

Registered spec: docs/SUICA_DEFENSE_PHASE_PLAN.md section "D1 -- Prospective
seal #2: the measured laws must predict, not describe" (REGISTERED 2026-08-10,
BEFORE RUN, commit 4dad82e).  Charter: docs/SUICA_DEFENSE_PHASE_CHARTER.md.

Executor standing: implementation and execution ONLY.  The registration text
is binding.  Everything labelled "RN-D1-n" is a register-note -- a standing
rule-9 operationalization of something the registration left open -- fixed and
written to reports/SUICA_D1_PROSPECTIVE_SEAL_REPORT.md Part 0 BEFORE the seal
was produced.

WHAT THIS LEG DOES.  It computes five quantitative predictions (S-1..S-5) for
configurations NOBODY HAS RUN, from PUBLISHED constants and PUBLISHED formulas
only, salts them, hashes them, and commits ONLY the hash.  A future registered
D-open leg runs the five configurations FRESH, adjudicates against the sealed
bands BEFORE unsealing, then unseals and verifies the hash.

G1D PURITY (rule-3 analogue, the whole point of a prospective seal).  THIS LEG
GENERATES NO WORLD OF ANY KIND.  Enforced in code, not by assertion in prose:
  (a) every world/panel generator in the reuse graph is REPLACED by a raising
      stub before any entry is computed (see WORLD_GENERATORS below), so a call
      is a crash, not a silent pass;
  (b) every numpy RNG entry point is wrapped by a caller-attributing logger
      that records which SUICA file:line asked for randomness; the log is
      written into the report and into the sealed bundle.
The only SUICA-attributed RNG call the five entries reach is disclosed in the
report as purity note D1-PN-1 (the FROZEN GAUGE DIRECTIONS, a frozen operator
constant reached through k2b.layout(); it is not a world, not a response panel,
and is independent of every knob this leg varies).

Reuse boundary (standing rule 12 -- SOURCE OBJECTS with file:line, not knob
names).  This leg calls, and does not reimplement:
  k2c.predicted_attenuation            (k2c:186-191)  "Pure algebra: no world
                                                       is generated."
  k2b.arm_shares                       (k2b:212-213)
  k2b.arm_predictions                  (k2b:533-583)  the K2a-validated
                                                       attenuation algebra
  k2e.person_share_design              (k2e:234-241)  V_person in the EXACT
                                                       currency kappa was fit in
  k2a.ar_set_var / ar_cross_cov        (k2a:282-300)  via arm_predictions
  l1.identity_only_z                   (l1:197-206)   the Delta-FREE boundary-z
  l1.SIGMA_TAU2_PER_DELTA2             (l1:194)       regular-simplex constant
  l2.SB2_RHO55 / L1_DELTA / K_TAU      (l2:128/111/102)
  l2.predicted_boundary_error_l2       (l2:384-416)   the eta-floor law -- read
                                                       for its LATENT reduction
                                                       only (RN-D1-3); NOT
                                                       called, because its card-
                                                       space realization needs a
                                                       world's loadings
  op31.content_hash                    (op31:64-65)   the sealing mechanic
No file outside this one is modified.  suica_core is NOT touched.

Usage:
  python scripts/run_suica_d1_prospective_seal.py --seal
  python scripts/run_suica_d1_prospective_seal.py --verify   (G2D only)
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import inspect
import json
import math
import os
import secrets
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

OUT = ROOT / "results" / "d1_sealed"
BUNDLE = OUT / "D1_SEALED_BUNDLE.json"
PUBLIC = OUT / "D1_PUBLIC_HASH.json"
REPORT = ROOT / "reports" / "SUICA_D1_PROSPECTIVE_SEAL_REPORT.md"

BANNER = ("prediction arithmetic on published constants; NO world of any kind "
          "is generated by this leg")

# --- registration-fixed configurations (docs/SUICA_DEFENSE_PHASE_PLAN.md:32-48)
S1_CONFIG = {"m": 96, "k_tau": 4, "G": 5, "n_occ": 8,
             "energy": "rho.55-equivalent", "eta_levels": [0.0, 0.5, 1.0]}
S2_CONFIG = {"m": 96, "k_tau": 4}
S3_CONFIG = {"settings": [[48, 512], [192, 256]],
             "baseline_d_n": [48, 512],
             "labels": ["known empty", "conjectured open"]}
S4_CONFIG = {"share": 0.40, "phi": 0.90, "w_int_arm": "zero",
             "instrument": "K2b (985-author K1-pinned panel, F2 m-multiset, "
                           "4 contexts)"}
S5_CONFIG = {"eta": 0.6, "energy": "rho.45-equivalent"}

# --- RN-D1-6/7/8 (rule 9): the band constants, pinned by WRITTEN RULE before
#     any value was computed.  Every one is DERIVED from a persisted record,
#     never chosen by eye.
S1_BAND_SAFETY = 2.0        # RN-D1-6
S1_FLOOR_PRED_MIN = 1e-3    # cells above this get the RELATIVE band
S1_ZERO_PRED_MAX = 1e-6     # cells below this get the ABSOLUTE band
S1_ZERO_ABS_BAND = 1e-3     # RN-D1-6b: the 8x512-author x per-boundary grain
S3_BAND_MULTIPLIER = 2.0    # RN-D1-7: S-3's band is 2x S-1's (conjecture-grade)
S4_BAND_SAFETY = 2.0        # RN-D1-8

# ---------------------------------------------------------------------------
# G1D: the purity harness.  Installed BEFORE the K/L-line modules are imported.

RNG_LOG: list[dict[str, Any]] = []
GENERATOR_CALLS: list[str] = []
_PHASE = {"name": "import"}

# every world / panel / card generator in the reuse graph, by module attribute
WORLD_GENERATORS = {
    "k2a": ("build_world", "response_panel", "card", "centered_channels"),
    "l1": ("build_typed_world", "type_geometry", "latent_identity",
           "cards_for_variant", "run_world_cells"),
    "l2": ("type_geometry_l2", "latent_identity_l2", "typed_trait_l2",
           "cards_for_cell", "build_typed_world_l2", "measure_cell_world"),
}


FOREIGN_RNG = {"n": 0}


def _suica_caller() -> str | None:
    """The IMMEDIATE caller of the RNG entry point, and only if it is a SUICA
    file.  Attributing to the immediate frame (not the first non-library frame
    below it) is what separates SUICA's own randomness from a third-party
    library's: `scipy.stats` calls `default_rng` while building distribution
    docstrings, and a first-non-library walk would blame whichever SUICA line
    happened to `import scipy.stats`."""
    stack = inspect.stack()
    if len(stack) < 3:
        return None
    fr = stack[2]
    f = fr.filename
    if str(ROOT) in f and "/site-packages/" not in f \
            and Path(f).name != Path(__file__).name:
        return f"{Path(f).parent.name}/{Path(f).name}:{fr.lineno}"
    FOREIGN_RNG["n"] += 1
    return None


_ORIG_DEFAULT_RNG = np.random.default_rng
_ORIG_SEED = np.random.seed


def _logged_default_rng(*a, **k):
    who = _suica_caller()
    if who is not None:
        RNG_LOG.append({"entry": "np.random.default_rng", "caller": who,
                        "args": repr(a)[:80], "phase": _PHASE["name"]})
    return _ORIG_DEFAULT_RNG(*a, **k)


def _logged_seed(*a, **k):
    who = _suica_caller()
    if who is not None:
        RNG_LOG.append({"entry": "np.random.seed", "caller": who,
                        "args": repr(a)[:80], "phase": _PHASE["name"]})
    return _ORIG_SEED(*a, **k)


np.random.default_rng = _logged_default_rng
np.random.seed = _logged_seed


def _raising_stub(name: str):
    def _f(*a, **k):
        GENERATOR_CALLS.append(name)
        raise SystemExit(
            f"G1D PURITY VIOLATION -- STOP: {name} was called.  This leg "
            "generates no world of any kind; see the registration's G1D.")
    return _f


def _load(mod_name: str):
    path = ROOT / "scripts" / f"{mod_name}.py"
    spec = importlib.util.spec_from_file_location(mod_name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[mod_name] = mod
    spec.loader.exec_module(mod)
    return mod


def install_generator_guards(mods: dict[str, Any]) -> list[str]:
    """Replace every world/panel generator by a raising stub.  Returns the list
    of guards actually installed (reported, so the attestation is auditable)."""
    installed = []
    for key, names in WORLD_GENERATORS.items():
        mod = mods.get(key)
        if mod is None:
            continue
        for n in names:
            if hasattr(mod, n):
                setattr(mod, n, _raising_stub(f"{key}.{n}"))
                installed.append(f"{key}.{n}")
    return installed


# ---------------------------------------------------------------------------
# G0D: provenance.  Every constant round-trip parsed from its persisted file,
# compared BIT-EXACTLY against the value the prediction arithmetic uses.

def _dig(obj: Any, path: str) -> Any:
    cur = obj
    for part in path.split("/"):
        if part == "":
            continue
        if isinstance(cur, list):
            cur = cur[int(part)]
        else:
            cur = cur[part]
    return cur


def _read_json(rel: str) -> Any:
    p = ROOT / rel
    if not p.exists():
        raise SystemExit(f"G0D FAIL: missing provenance file {rel}")
    return json.loads(p.read_text(encoding="utf-8"))


def provenance_table() -> tuple[dict[str, float], list[dict[str, Any]]]:
    """Round-trip every constant.  Returns (values, table)."""
    spec = [
        # name, file, json path, expected literal (from the registration text)
        ("lambda", "results/m4_k2d_frontier_carrier/decision.json",
         "leans/q_update/lambda", 0.17417497661611914),
        ("q", "results/m4_k2d_frontier_carrier/decision.json",
         "leans/q_update/q", 1.8528700746510731),
        ("kappa_hat", "results/m4_k2d_frontier_carrier/post_hoc_descriptive.json",
         "kappa_ols_through_origin", -0.7220359963712748),
        ("kappa_hat_k2e_reverify", "results/m4_k2e_double_matching/decision.json",
         "G0e_anchors/kappa_companion/kappa_rederived", -0.7220359963712748),
        ("kappa_resid_max_9pair", "results/m4_k2e_double_matching/decision.json",
         "kappa_refit_9pairs/max_abs_residual", 0.008917886817207595),
        ("delta_L1", "results/m4_l1_typed_world/decision.json",
         "delta", 5.928950380606693),
        ("sigma_b2_rho55eq", "results/m4_l3_taxometer_meter/decision.json",
         "sigma_b2/rho55eq", 16.111540782194115),
        ("sigma_b2_rho35eq", "results/m4_l3_taxometer_meter/decision.json",
         "sigma_b2/rho35eq", 7.098091393554051),
        ("delta_amb03_L2", "results/m4_l2_threshold_continuum/gates.json",
         "G2M/rule18_joint/clause_delta_intervals/W-1a (ambient < 0.30)/1",
         2.6977587972014083),
        ("delta_orc80_L2", "results/m4_l2_threshold_continuum/gates.json",
         "G2M/rule18_joint/clause_delta_intervals/W-1a (oracle-S > 0.80)/0",
         4.238555648405859),
        ("k_latent_L2", "results/m4_l2_threshold_continuum/gates.json",
         "k_latent", 48),
        ("n_authors_L2", "results/m4_l2_threshold_continuum/gates.json",
         "n_authors", 512),
        ("k_tau_L2", "results/m4_l2_threshold_continuum/gates.json", "k_tau", 3),
        ("taxometer_tolerance", "results/m4_l3_taxometer_meter/decision.json",
         "leans/X-2/tolerance", 0.125),
    ]
    values: dict[str, float] = {}
    table: list[dict[str, Any]] = []
    for name, rel, path, expected in spec:
        got = _dig(_read_json(rel), path)
        bit_exact = (got == expected)
        values[name] = got
        table.append({"constant": name, "file": rel, "field": path,
                      "round_trip_value": got, "registration_literal": expected,
                      "residual": (float(got) - float(expected)),
                      "bit_exact": bool(bit_exact)})
    return values, table


def module_constant_checks(mods: dict[str, Any], v: dict[str, float]) -> list[dict]:
    """The same constants as they are HARD-CODED in the source objects, so a
    drift between the persisted artifact and the script would be caught."""
    l1, l2, k2a = mods["l1"], mods["l2"], mods["k2a"]
    rows = [
        ("l2.L1_DELTA", "scripts/run_suica_m4_l2_threshold_continuum.py:111",
         l2.L1_DELTA, v["delta_L1"]),
        ("l2.SB2_RHO55", "scripts/run_suica_m4_l2_threshold_continuum.py:128",
         l2.SB2_RHO55, v["sigma_b2_rho55eq"]),
        ("l2.SB2_RHO35", "scripts/run_suica_m4_l2_threshold_continuum.py:129",
         l2.SB2_RHO35, v["sigma_b2_rho35eq"]),
        ("l2.K_TAU", "scripts/run_suica_m4_l2_threshold_continuum.py:102",
         l2.K_TAU, v["k_tau_L2"]),
        ("k2a.K_LATENT", "scripts/run_suica_m4_k2a_expressive_world.py:89",
         k2a.K_LATENT, v["k_latent_L2"]),
        ("l1.SIGMA_TAU2_PER_DELTA2",
         "scripts/run_suica_m4_l1_typed_world.py:194",
         l1.SIGMA_TAU2_PER_DELTA2, 3.0 / 8.0),
    ]
    return [{"object": n, "source": s, "value": a, "matches": bool(a == b),
             "against": b} for n, s, a, b in rows]


def algebra_round_trip(mods: dict[str, Any]) -> list[dict[str, Any]]:
    """G0D, second half: the FORMULAS, not just the constants.  Re-derive two
    persisted K2c/K2d arms through the very functions S-4 uses and demand
    bit-exactness against what those legs wrote to disk."""
    k2c, k2e = mods["k2c"], mods["k2e"]
    rows = []
    part0 = _read_json("results/m4_k2c_matched_pairs/part0_arms.json")
    posth = _read_json("results/m4_k2d_frontier_carrier/post_hoc_descriptive.json")
    pv = {(r["leg"], r["pair"]): r for r in posth["rows"]}
    for pair in part0["pairs"]:
        a = pair["arm_a"]
        r_re = k2c.predicted_attenuation(a["share"], a["phi"])
        row = {"arm": a["arm"], "share": a["share"], "phi": a["phi"],
               "r_persisted": a["predicted_attenuation"], "r_rederived": r_re,
               "r_bit_exact": bool(r_re == a["predicted_attenuation"])}
        rec = pv.get(("K2c", pair["pair"]))
        if rec is not None:
            vp = k2e.person_share_design(a["share"], 0.0)
            row["V_person_persisted"] = rec["person_var_a"]
            row["V_person_rederived"] = vp
            row["V_person_bit_exact"] = bool(vp == rec["person_var_a"])
        rows.append(row)
    return rows


# ---------------------------------------------------------------------------
# The five entries.  PREDICTION ARITHMETIC ONLY.

def _phi_lower_tail(z: float) -> float:
    """Phi(-z) = 0.5 erfc(z/sqrt(2)) -- l2:415's own expression, verbatim."""
    return 0.5 * math.erfc(z / math.sqrt(2.0))


def sigma_u2(eta: float, sigma_b2: float, k_tau: int, m: int) -> float:
    """Appendix R.1 / L2 derivation 2, l2:392-394 and l2:934-936:
        sigma_u^2(eta) = eta sigma_b^2/k_tau + (1-eta) sigma_b^2/m."""
    return eta * sigma_b2 / k_tau + (1.0 - eta) * sigma_b2 / m


def s1_band_constant(w3: dict[str, Any]) -> dict[str, Any]:
    """RN-D1-6: S-1's relative band = S1_BAND_SAFETY x (the MAX observed
    relative deviation of measured-from-predicted over L2's ten-cell W-3
    containment record, restricted to cells whose PREDICTED rate is at least
    S1_FLOOR_PRED_MIN -- the regime S-1's non-degenerate entries live in;
    the sub-1e-6 cells are numerically degenerate and get an ABSOLUTE band)."""
    meas, pred = w3["measured"], w3["predicted"]
    devs = {}
    for cell, p in pred.items():
        if p >= S1_FLOOR_PRED_MIN:
            devs[cell] = abs(meas[cell] - p) / p
    worst_cell = max(devs, key=devs.get)
    return {"per_cell_relative_deviation": devs,
            "worst_cell": worst_cell, "max_relative_deviation": devs[worst_cell],
            "safety_factor": S1_BAND_SAFETY,
            "relative_band": S1_BAND_SAFETY * devs[worst_cell],
            "absolute_band_for_degenerate_cells": S1_ZERO_ABS_BAND,
            "n_cells_used": len(devs), "n_cells_total": len(pred)}


def entry_s1(v: dict[str, float], band: dict[str, Any]) -> dict[str, Any]:
    """S-1: the eta-floor curve at m=96, k_tau=4, G=5, n_occ=8, rho.55-eq."""
    m, k_tau = S1_CONFIG["m"], S1_CONFIG["k_tau"]
    delta, sb2 = v["delta_L1"], v["sigma_b2_rho55eq"]
    primary = {}
    for eta in S1_CONFIG["eta_levels"]:
        su2 = sigma_u2(eta, sb2, k_tau, m)
        z = delta / (2.0 * math.sqrt(su2))
        rate = _phi_lower_tail(z)
        if rate >= S1_FLOOR_PRED_MIN:
            b = {"kind": "relative", "band": band["relative_band"],
                 "lo": rate * (1.0 - band["relative_band"]),
                 "hi": rate * (1.0 + band["relative_band"])}
        elif rate <= S1_ZERO_PRED_MAX:
            b = {"kind": "absolute", "band": S1_ZERO_ABS_BAND,
                 "lo": 0.0, "hi": S1_ZERO_ABS_BAND}
        else:
            b = {"kind": "relative(intermediate)", "band": band["relative_band"],
                 "lo": rate * (1.0 - band["relative_band"]),
                 "hi": rate * (1.0 + band["relative_band"])}
        primary[f"eta{eta:g}"] = {"sigma_u2": su2, "boundary_z": z,
                                  "predicted_per_boundary_rate": rate,
                                  "falsification_band": b}
    # RN-D1-4 companion: the Delta-FREE rho-parameterized form made INTERNALLY
    # consistent with G=5's own regular-simplex constant c_G = (G-1)/(2G).
    g = S1_CONFIG["G"]
    c_g = (g - 1) / (2.0 * g)
    rho = 0.55
    companion = {}
    for eta in S1_CONFIG["eta_levels"]:
        # z(eta) = (Delta/2) / sigma_u(eta), sigma_b^2 = c_G Delta^2 rho/(1-rho)
        inv_dims = eta / k_tau + (1.0 - eta) / m
        z = 1.0 / (2.0 * math.sqrt(c_g * rho / (1.0 - rho) * inv_dims))
        companion[f"eta{eta:g}"] = {"boundary_z": z,
                                    "predicted_per_boundary_rate":
                                        _phi_lower_tail(z)}
    return {
        "id": "S-1",
        "title": "eta-floor curve at an unrun config",
        "grade": "MEASURED-LAW",
        "config": dict(S1_CONFIG),
        "formula": ("per-boundary rate = Phi(-Delta/(2 sigma_u(eta))), "
                    "sigma_u^2(eta) = eta sigma_b^2/k_tau + (1-eta) sigma_b^2/m"),
        "formula_source": ("scripts/run_suica_m4_l2_threshold_continuum.py:"
                           "384-416 (predicted_boundary_error_l2 docstring's "
                           "LATENT reduction, l2:391-393) and l2:934-936; "
                           "IDT appendix R.1 / Q.1"),
        "constants": {"Delta": delta, "sigma_b2": sb2},
        "primary": primary,
        "companion_delta_free_G5_consistent": companion,
        "band_rule": band,
    }


def entry_s2(v: dict[str, float]) -> dict[str, Any]:
    """S-2: the boundary z-ratio sqrt(m/k_tau) and the ARI-drop direction."""
    m, k_tau = S2_CONFIG["m"], S2_CONFIG["k_tau"]
    ratio = math.sqrt(m / k_tau)
    return {
        "id": "S-2",
        "title": "tax ratio at the same unrun config",
        "grade": "EXACT-ALGEBRA",
        "config": dict(S2_CONFIG),
        "formula": ("z(eta=0)/z(eta=1) = sigma_u(1)/sigma_u(0) = sqrt(m/k_tau) "
                    "-- Delta-free, rho-free, G-free"),
        "formula_source": ("scripts/run_suica_m4_l1_typed_world.py:197-206 "
                           "(identity_only_z: 'the SNR factor m/k_tau of R2 is "
                           "the ratio of the two z^2')"),
        "predicted_z_ratio": ratio,
        "predicted_z2_ratio": float(m) / k_tau,
        "falsification_band": {
            "kind": "sign/ordering (rule 19: the law's own quantity is a "
                    "RATIO and an ORDER, not a tolerance)",
            "algebraic_tolerance": 1e-12,
            "direction_claim": ("ARI DROPS as eta rises: ARI(eta=1) < "
                                "ARI(eta=0.5) < ARI(eta=0) strictly, and the "
                                "per-boundary error rate is strictly "
                                "INCREASING in eta, at the rho.55-equivalent"),
            "kill_condition": ("any reversal in the eta-ordering of either the "
                               "rate or the ARI, or a measured z-ratio outside "
                               "the algebraic tolerance"),
        },
    }


def entry_s3(v: dict[str, float], s1_band: dict[str, Any]) -> dict[str, Any]:
    """S-3: localization-window widths at two (d/n) settings.  CONJECTURE."""
    d0, n0 = S3_CONFIG["baseline_d_n"]
    lo_edge = v["delta_orc80_L2"]          # projection-invariant (appendix Q.1)
    amb0 = v["delta_amb03_L2"]
    rel = S3_BAND_MULTIPLIER * s1_band["relative_band"]
    settings = []
    for (d, n), label in zip(S3_CONFIG["settings"], S3_CONFIG["labels"]):
        scale = ((d / n) / (d0 / n0)) ** 0.25
        hi_edge = amb0 * scale
        width = hi_edge - lo_edge
        settings.append({
            "d": d, "n": n, "registration_label": label,
            "gamma": d / n, "scale_vs_baseline": scale,
            "predicted_lower_edge_delta": lo_edge,
            "predicted_upper_edge_delta": hi_edge,
            "predicted_window_width": width,
            "predicted_state": "OPEN" if width > 0.0 else "EMPTY",
            "falsification_band": {
                "kind": "interval, conjecture-grade",
                "relative_band_on_each_edge": rel,
                "lower_edge_interval": [lo_edge * (1 - rel), lo_edge * (1 + rel)],
                "upper_edge_interval": [hi_edge * (1 - rel), hi_edge * (1 + rel)],
                "primary_falsifier": ("the BINARY open/empty call at this "
                                      "setting"),
            },
        })
    return {
        "id": "S-3",
        "title": "localization-window widths at two (d/n) settings",
        "grade": "CONJECTURE-GRADE -- a miss kills the (d/n)^(1/4) window "
                 "conjecture, NOT the measured floor/tax laws",
        "config": dict(S3_CONFIG),
        "formula": ("BBP energy criterion: a between-type spike lambda = "
                    "Delta_card^2/8 is found against bulk sigma^2 iff lambda > "
                    "sigma^2 sqrt(d/n), so the AMBIENT break scales as "
                    "Delta ~ sigma (d/n)^(1/4); the ORACLE-S / Bayes-ceiling "
                    "edge is projection-INVARIANT (appendix Q.1) and therefore "
                    "does NOT scale with (d,n).  Window = [oracle-S>0.80 edge, "
                    "ambient<0.30 edge]."),
        "formula_source": ("scripts/run_suica_m4_l2_threshold_continuum.py:"
                           "878-900 (W-1 fidelity row, the energy criterion and "
                           "the (k_tau/DIM)^(1/4) factor); baseline edges from "
                           "results/m4_l2_threshold_continuum/gates.json"),
        "baseline": {"d": d0, "n": n0,
                     "ambient_lt_0.30_edge": amb0,
                     "oracleS_gt_0.80_edge": lo_edge,
                     "L2_measured_window_satisfiable": False},
        "settings": settings,
        "band_derivation": {"multiplier_on_S1_band": S3_BAND_MULTIPLIER,
                            "S1_relative_band": s1_band["relative_band"],
                            "S3_relative_band": rel},
    }


def entry_s4(mods: dict[str, Any], v: dict[str, float]) -> dict[str, Any]:
    """S-4: the variance-tax law at a NEW state arm on the K2b instrument."""
    k2c, k2e = mods["k2c"], mods["k2e"]
    share, phi = S4_CONFIG["share"], S4_CONFIG["phi"]
    r = k2c.predicted_attenuation(share, phi)
    v_person = k2e.person_share_design(share, 0.0)
    lam, q, kap = v["lambda"], v["q"], v["kappa_hat"]
    level = lam * (r ** q)
    field = level + kap * v_person          # kappa_hat is NEGATIVE (the tax)
    band = S4_BAND_SAFETY * v["kappa_resid_max_9pair"]
    return {
        "id": "S-4",
        "title": "variance-tax law at a new state arm",
        "grade": "MEASURED-LAW",
        "config": dict(S4_CONFIG),
        "formula": "field ~ lambda * r^q - kappa * V_person",
        "formula_source": ("scripts/run_suica_m4_k2e_double_matching.py:3 "
                           "(H-VAR statement) and :234-241 "
                           "(person_share_design); r from "
                           "scripts/run_suica_m4_k2c_matched_pairs.py:186-191 "
                           "(predicted_attenuation -> k2b:533-583)"),
        "constants": {"lambda": lam, "q": q, "kappa_hat": kap},
        "inputs": {"r_predicted_attenuation": r, "V_person_design_share": v_person},
        "predicted_level_term": level,
        "predicted_b_only_field_recovery": field,
        "falsification_band": {
            "kind": "absolute, on the field quantity",
            "source": ("results/m4_k2e_double_matching/decision.json "
                       "kappa_refit_9pairs/max_abs_residual over the 9 "
                       "K2c+K2d+K2e pairs"),
            "residual_record": v["kappa_resid_max_9pair"],
            "safety_factor": S4_BAND_SAFETY,
            "band": band, "lo": field - band, "hi": field + band,
        },
    }


def entry_s5(v: dict[str, float]) -> dict[str, Any]:
    """S-5: the taxometer at a new eta = 0.6, rho.45-equivalent cell."""
    # the rho.45-equivalent energy, by L2's OWN published mapping (l2:127-129)
    sigma_tau2 = (3.0 / 8.0) * v["delta_L1"] * v["delta_L1"]
    sb2_rho45 = sigma_tau2 * 0.45 / 0.55
    eta = S5_CONFIG["eta"]
    tol = v["taxometer_tolerance"]
    l3 = _read_json("results/m4_l3_taxometer_meter/decision.json")
    poles = {c: rec["eta_hat"] for c, rec in l3["leans"]["X-2"]["per_cell"].items()
             if rec["eta"] == 0.0}
    return {
        "id": "S-5",
        "title": "taxometer reading at a new (eta, energy) cell",
        "grade": "MEASURED-LAW (certified instrument)",
        "config": dict(S5_CONFIG),
        "formula": ("the L3 spectral taxometer reads eta: eta_hat = eta within "
                    "its CERTIFIED budget"),
        "formula_source": ("scripts/run_suica_m4_l3_taxometer_meter.py:126 "
                           "(X2_TOL) and results/m4_l3_taxometer_meter/"
                           "decision.json leans/X-2 (10/10 within tolerance)"),
        "cell_energy_sigma_b2": sb2_rho45,
        "predicted_eta_hat": eta,
        "falsification_band": {
            "kind": "absolute, the CERTIFIED budget",
            "band": tol, "lo": eta - tol, "hi": eta + tol,
            "certification": "L3 X-2 HOLD, 10/10 cells within +-0.125",
            "pole_bias_note": {
                "statement": ("L3's record carries a known POSITIVE bias of "
                              "O(0.05) at the eta=0 pole; eta=0.6 is INTERIOR, "
                              "so the note is CARRIED, not applied -- the "
                              "predicted point stays eta"),
                "observed_eta0_readings": poles,
            },
        },
    }


# ---------------------------------------------------------------------------
# The seal.  OP-31's content_hash mechanic (op31:64-65), SALTED per the
# registration's pre-declared fallback.

def content_hash(obj: Any) -> str:
    """op31:64-65, verbatim mechanic."""
    return hashlib.sha256(json.dumps(obj, sort_keys=True).encode()).hexdigest()


def salted_hash(salt: str, obj: Any) -> str:
    """D1's extension of op31:64-65: the salt is prefixed to the canonical
    JSON before hashing.  Re-verification recipe (for the D-open leg):
        sha256((salt + json.dumps(predictions, sort_keys=True)).encode())"""
    payload = salt + json.dumps(obj, sort_keys=True)
    return hashlib.sha256(payload.encode()).hexdigest()


OPENING_PROTOCOL = [
    "The seal opens ONLY in a future registered leg (D-open).",
    "Trigger: the program owner's request, or the defense phase reaching D4, "
    "whichever comes first.",
    "(1) D-open RUNS the five configurations FRESH and writes its measured "
    "values to disk BEFORE any unsealing.",
    "(2) D-open then adjudicates each measured value against the sealed band "
    "-- the bands are inside the bundle, so the adjudication rule is fixed "
    "before it is read.",
    "(3) D-open unseals: it reads results/d1_sealed/D1_SEALED_BUNDLE.json, "
    "recomputes sha256((salt + json.dumps(bundle['predictions'], "
    "sort_keys=True)).encode()).hexdigest(), and requires it to equal the "
    "hash committed in reports/SUICA_D1_PROSPECTIVE_SEAL_REPORT.md.  A "
    "mismatch is SEAL-TAMPERED and the whole seal is void.",
    "(4) D-open scores each entry PREDICTED / MISSED with NO re-fitting and "
    "NO post-hoc band edits.",
    "(5) S-3 is CONJECTURE-GRADE: its miss kills the (d/n)^(1/4) window "
    "conjecture only.  S-1/S-2/S-4/S-5 misses fall on the measured laws.",
    "If the bundle is lost, the seal is void and must be declared void -- a "
    "lost bundle is NOT evidence for or against any entry.",
]


# ---------------------------------------------------------------------------

def build_part0(prov: list[dict], modchecks: list[dict], algebra: list[dict],
                guards: list[str], started: str) -> str:
    def _row(d, keys):
        return "| " + " | ".join(f"`{d[k]}`" for k in keys) + " |"

    lines = [
        "# SUICA D1 — Prospective seal #2 (report)",
        "",
        f"Banner: **{BANNER}**",
        "",
        "Registration: `docs/SUICA_DEFENSE_PHASE_PLAN.md` section "
        "\"D1 — Prospective seal #2\" (REGISTERED 2026-08-10, BEFORE RUN, "
        "commit `4dad82e`). Charter: `docs/SUICA_DEFENSE_PHASE_CHARTER.md`. "
        "Executor standing: implementation and execution only.",
        "",
        "**This report never carries a sealed value.** It carries the "
        "protocol, the provenance, the purity attestation, the entry "
        "STRUCTURE (which entries, which band rules), the HASH, and the "
        "opening protocol. The values live only in the gitignored bundle.",
        "",
        f"Part 0 written at `{started}` — BEFORE the seal was produced.",
        "",
        "---",
        "",
        "## Part 0.1 — Protocol authority and the disclosed deviation",
        "",
        "OP-31 (\"prospective seal #1, the time lockbox\") was LOCATED:",
        "",
        "- human copy of record: `docs/OP31_PROSPECTIVE_SEAL.md` (tracked; "
        "carries `self_sha256` and the plaintext predictions)",
        "- machine copy / harness: "
        "`scripts/run_suica_op31_prospective_seal_v1.py` (the `PREDICTIONS` "
        "dict at op31:49-61, the sealing mechanic at op31:64-65, the "
        "tamper check at op31:84-85)",
        "- OP-31's own artifact directory "
        "`results/suica_op31_prospective_seal_v1/PROSPECTIVE_SEAL.json` does "
        "NOT exist on this machine, and `results/` is gitignored in full "
        "(`.gitignore:2`), so OP-31's seal of record is in practice the "
        "tracked DOC plus the tracked script constant.",
        "",
        "**Mechanic ADOPTED from OP-31 (op31:64-65):** the content hash is "
        "`sha256(json.dumps(obj, sort_keys=True).encode()).hexdigest()` over "
        "the canonical, key-sorted JSON of the prediction object. D1 uses "
        "exactly this, with the salt prefixed to the canonical JSON.",
        "",
        "**Concealment model INCOMPATIBLE — deviation disclosed.** OP-31 "
        "could commit its predictions IN PLAINTEXT because they concerned "
        "text not yet written: no one could peek, so no one could back-fit. "
        "D1's five configurations are runnable TODAY. Publishing them in "
        "plaintext would destroy the seal's whole value. D1 therefore takes "
        "the registration's PRE-DECLARED FALLBACK "
        "(`docs/SUICA_DEFENSE_PHASE_PLAN.md:24-28`): salted SHA-256; the "
        "sealed plaintext bundle under `results/d1_sealed/` (gitignored); "
        "ONLY the hash, the salt-handling statement, the provenance table and "
        "the opening protocol are committed. The hash MECHANIC is OP-31's; "
        "the STORAGE model is the fallback's. That split is the deviation.",
        "",
        "**Salt handling.** The salt is 32 cryptographically random bytes "
        "(`secrets.token_hex(32)`), generated once at seal time. It is stored "
        "ONLY inside the gitignored bundle, next to the plaintext it salts. "
        "It is never committed, never printed to the terminal, and never "
        "quoted in this report. Its only purpose is to make the committed "
        "hash non-invertible by dictionary search over plausible prediction "
        "tables — without it, an adversary who guessed the schema could "
        "brute-force five numbers. Losing the salt voids the seal exactly as "
        "losing the bundle does.",
        "",
        "**COPY INSTRUCTION FOR THE PROGRAM OWNER (required — the bundle is "
        "gitignored and therefore unbacked):**",
        "",
        "```",
        "cp -p 'results/d1_sealed/D1_SEALED_BUNDLE.json' <somewhere outside "
        "this repo, e.g. an encrypted volume or a password manager note>",
        "```",
        "",
        "Keep at least one copy off this machine. The D-open leg needs the "
        "bundle AND its salt; this report's hash is only the tamper check.",
        "",
        "## Part 0.2 — G0D provenance table (every constant round-trip parsed)",
        "",
        "| constant | file | field | round-trip value | registration literal | "
        "residual | bit-exact |",
        "|---|---|---|---|---|---|---|",
    ]
    for d in prov:
        lines.append(
            f"| `{d['constant']}` | `{d['file']}` | `{d['field']}` | "
            f"`{d['round_trip_value']!r}` | `{d['registration_literal']!r}` | "
            f"`{d['residual']!r}` | {'**YES**' if d['bit_exact'] else '**NO**'} |")
    lines += [
        "",
        "Two provenance corrections to the registration text, disclosed rather "
        "than silently followed:",
        "",
        "1. **κ's persisted home.** The registration cites "
        "`results/m4_k2d_frontier_carrier/decision.json (kappa fit)`. That "
        "file contains NO κ field. The fit lives in the sibling "
        "`results/m4_k2d_frontier_carrier/post_hoc_descriptive.json` under "
        "`kappa_ols_through_origin`, and K2e re-derived it bit-exactly "
        "(`G0e_anchors/kappa_companion/kappa_rederived`, residual `0.0`). Same "
        "leg, same number, different file — the table above cites the real "
        "field and carries the K2e re-verification as its own row.",
        "2. **κ's SIGN.** Every persisted field stores `-0.7220359963712748`; "
        "the registration writes `κ = 0.7220359963712748` in the law "
        "`field ≈ λ·r^q − κ·V_person`, i.e. κ is the positive magnitude of a "
        "SUBTRACTED tax. This leg uses the persisted signed value with a `+`, "
        "which is the same arithmetic; the convention is pinned as RN-D1-9.",
        "",
        "**Unavoidable overlap between the provenance table and one sealed "
        "quantity, disclosed.** G0D requires the constants above to be "
        "committed. Two of them — `delta_orc80_L2` and `delta_amb03_L2` — are "
        "ALSO, by the S-3 formula and with no arithmetic in between, S-3's "
        "predicted lower edge (which is `(d, n)`-invariant by appendix Q.1) "
        "and S-3's predicted upper edge AT THE BASELINE SETTING `(48, 512)`. "
        "The registration itself already labels that setting \"known empty\", "
        "so nothing secret is disclosed by the coincidence. S-3's genuinely "
        "sealed content is the `(192, 256)` setting: its scale factor, its "
        "upper edge, its width and its OPEN/EMPTY call appear nowhere in this "
        "report. A mechanical leak check enforces this and is reported in "
        "Part 1.",
        "",
        "### Source-object constants (drift check against the persisted files)",
        "",
        "| source object | file:line | value | matches persisted |",
        "|---|---|---|---|",
    ]
    for d in modchecks:
        lines.append(f"| `{d['object']}` | `{d['source']}` | `{d['value']!r}` | "
                     f"{'**YES**' if d['matches'] else '**NO**'} |")
    lines += [
        "",
        "### G0D, second half — the FORMULAS round-tripped, not just the numbers",
        "",
        "S-4 is the only entry whose value comes out of executable published "
        "machinery rather than closed-form arithmetic, so the machinery itself "
        "is round-tripped: the K2c pair arms are re-derived through the very "
        "functions S-4 calls and compared bit-exactly with what K2c/K2d wrote "
        "to disk.",
        "",
        "| arm | share | φ | r persisted | r re-derived | bit-exact | "
        "V_person persisted | V_person re-derived | bit-exact |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for d in algebra:
        lines.append(
            f"| `{d['arm']}` | `{d['share']!r}` | `{d['phi']!r}` | "
            f"`{d['r_persisted']!r}` | `{d['r_rederived']!r}` | "
            f"{'**YES**' if d['r_bit_exact'] else '**NO**'} | "
            f"`{d.get('V_person_persisted')!r}` | "
            f"`{d.get('V_person_rederived')!r}` | "
            f"{'**YES**' if d.get('V_person_bit_exact') else '**NO**'} |")
    lines += [
        "",
        "## Part 0.3 — G1D purity statement (enforced in code)",
        "",
        "The registration's G1D: *THIS LEG GENERATES NO WORLD of any kind. "
        "Prediction arithmetic only. Any world generation is a defect → STOP.*",
        "",
        "Enforcement, not assertion:",
        "",
        "1. **Raising stubs.** Before any entry is computed, every world / "
        "panel / card generator in the reuse graph is REPLACED by a stub that "
        "raises `SystemExit`. A call would be a crash, not a silent pass. "
        "Guards installed this run: " + ", ".join(f"`{g}`" for g in guards) + ".",
        "2. **RNG attribution.** `np.random.default_rng` and `np.random.seed` "
        "are wrapped by a logger that reads the IMMEDIATE calling frame and "
        "records it only if that frame is a SUICA file. Immediate-frame "
        "attribution is deliberate: `scipy.stats` calls "
        "`default_rng(615681484984984)` dozens of times at import while "
        "building distribution docstrings, and a first-non-library stack walk "
        "would blame whichever SUICA line happened to `import scipy.stats`. "
        "Foreign calls are counted, not hidden. The full SUICA log and the "
        "foreign count are reproduced in Part 1 and stored in the bundle.",
        "",
        "**RN-D1-3 (rule 9) — why the LATENT floor and not `l2."
        "predicted_boundary_error_l2`.** L2's floor function is the "
        "CARD-SPACE realization: it needs `world['loadings']` and a realized "
        "type geometry, i.e. a generated world. Calling it would violate G1D. "
        "Its own docstring (l2:391-393) states that the card form *\"reduces "
        "to derivation 2's `sigma_u^2(eta) = eta sigma_b^2/k_tau + (1-eta) "
        "sigma_b^2/m` exactly when M is an isometry\"*. S-1 therefore seals "
        "the LATENT law — the theorem's own object (appendix R.1 / Q.1) — and "
        "the D-open leg must adjudicate against the latent form on a realized "
        "world, which is precisely the containment question L2's W-3 already "
        "answers 7/10 at its own config.",
        "",
        "**RN-D1-4 (rule 9) — what G=5 and n_occ=8 do and do not change.** "
        "For a regular simplex every pairwise boundary sits at `Delta/2` "
        "regardless of the number of vertices, so `G` changes the COUNT of "
        "boundaries (`C(5,2)=10`) and not the PER-BOUNDARY rate S-1 predicts. "
        "`n_occ` enters only the FULL-Bayes rate's slow/observation terms "
        "(l2:411-414); the identity-only FLOOR — the registered object — does "
        "not see it. Note also that the registered config is internally "
        "consistent: `k_tau = G - 1 = 4` is exactly the dimension a 5-vertex "
        "regular simplex spans, as `k_tau = 3` was for L1/L2's `G = 4`.",
        "",
        "**RN-D1-1/2 (rule 9) — what \"identity energy at the ρ.55-equivalent\" "
        "pins.** L2 introduced \"ρ.55-equivalent\" as a TERM OF ART for a fixed "
        "NUMBER, decoupled from Δ (l2:124-129: *\"L2 keeps Delta free and pins "
        "sigma_b^2 at the two ENERGIES L1 realized at its own Delta\"*). S-1's "
        "PRIMARY reading therefore transports `sigma_b^2 = SB2_RHO55` and "
        "`Delta = L1_DELTA` UNCHANGED to the new `(m, k_tau)`, exactly as L2's "
        "C-arm cells use them. Because the two readings of the phrase are both "
        "defensible, the second — the Δ-free `rho_id = 0.55` form made "
        "internally consistent with G=5's own simplex constant "
        "`c_5 = (G-1)/(2G) = 0.4` — is computed and sealed as a NAMED "
        "COMPANION inside S-1. The PRIMARY is named in the bundle; the "
        "companion cannot be promoted at opening time.",
        "",
        "**RN-D1-5 (rule 9) — S-3's `d`.** The registration's baseline setting "
        "`(48, 512)` is labelled \"known empty\", and L2's own measured window "
        "IS empty (`W1_window.satisfiable_anywhere_in_delta = false`) at "
        "`k_latent = 48`, `n_authors = 512`. `d` is therefore pinned as the "
        "LATENT working-space dimension `m` (k2a:89), not the card dimension "
        "`DIM = 64` (k2a:90) that L2's W-2 row used for its own `gamma`. The "
        "pin makes the registration's \"known empty\" label true by "
        "measurement rather than by extrapolation.",
        "",
        "## Part 0.4 — the band rules (rule 19: each band on the law's OWN "
        "quantity), pinned before any value",
        "",
        "| entry | law's own quantity | band rule | rule-9 note |",
        "|---|---|---|---|",
        "| S-1 | a per-boundary ERROR RATE | RELATIVE band = "
        f"`{S1_BAND_SAFETY}` × (max relative deviation of measured-from-"
        "predicted over L2's ten-cell W-3 containment record, restricted to "
        f"cells with predicted rate ≥ `{S1_FLOOR_PRED_MIN}`). Cells whose "
        f"predicted rate is ≤ `{S1_ZERO_PRED_MAX}` are numerically degenerate "
        f"and get an ABSOLUTE band `{S1_ZERO_ABS_BAND}` instead. | RN-D1-6. The "
        "restriction is stated, not fitted: the sub-1e-6 cells have no "
        "meaningful relative deviation (L2 measured exactly `0.0` at both "
        "η=0 cells), and including them would make the band infinite. |",
        "| S-2 | a RATIO and an ORDER | no numeric tolerance — the band is the "
        "ARI-drop DIRECTION plus a strict ordering claim in η, with a "
        "`1e-12` algebraic tolerance on the ratio itself. | RN-D1-9. S-2 is "
        "exact algebra; a numeric band would be a category error. |",
        "| S-3 | a Δ-INTERVAL (window edges and width) | interval predictions "
        f"with a relative band `{S3_BAND_MULTIPLIER}` × S-1's on EACH edge, "
        "plus a BINARY open/empty call as the primary falsifier. | RN-D1-7. "
        "The multiplier is derived, not chosen: the `(d/n)^(1/4)` law has "
        "never been tested ACROSS `(d, n)` in this program, only within one "
        "setting, so its band is twice the measured floor law's. |",
        "| S-4 | a FIELD value | ABSOLUTE band = "
        f"`{S4_BAND_SAFETY}` × the max ABSOLUTE RESIDUAL of the 9-pair "
        "K2c+K2d+K2e κ refit. | RN-D1-8. |",
        "| S-5 | an η̂ READING | ABSOLUTE band = the CERTIFIED `±0.125` (L3 "
        "X-2, 10/10 within), with the known `+O(0.05)` pole-bias CARRIED as a "
        "note: η=0.6 is interior, so the bias is not applied to the point "
        "prediction. | RN-D1-10. |",
        "",
        "The band constants are all DERIVED from persisted records at run "
        "time. The only free choices are the two safety factors and the "
        "S-3 multiplier, all fixed above before any value existed.",
        "",
        "---",
        "",
    ]
    return "\n".join(lines)


def build_part1(bundle_meta: dict, structure: list[dict], sha: str,
                gates: dict, timing: dict) -> str:
    lines = [
        "",
        "## Part 1 — the seal",
        "",
        "### The entry structure (NO values — the values are sealed)",
        "",
        "| entry | grade | configuration (from the registration) | what is "
        "sealed | band kind |",
        "|---|---|---|---|---|",
    ]
    for s in structure:
        lines.append(
            f"| **{s['id']}** | {s['grade'].split(' --')[0]} | "
            f"`{json.dumps(s['config'], sort_keys=True)}` | {s['sealed_what']} "
            f"| {s['band_kind']} |")
    lines += [
        "",
        "### Formulas, by source object (rule 12)",
        "",
    ]
    for s in structure:
        lines += [f"- **{s['id']}** — {s['formula']}",
                  f"  - source: {s['formula_source']}"]
    lines += [
        "",
        "### G1D purity attestation (this run)",
        "",
        f"- world/panel/card generator calls: **{gates['n_generator_calls']}**",
        f"- guards installed and armed: **{gates['n_guards']}**",
        f"- third-party (numpy/scipy) RNG calls, excluded by immediate-frame "
        f"attribution: `{gates['n_foreign_rng']}` "
        "(all from `scipy.stats`'s import-time docstring builder)",
        "- SUICA-attributed RNG calls, whole run:",
        "",
        "| phase | entry point | caller (file:line) | argument |",
        "|---|---|---|---|",
    ]
    if not gates["rng_log"]:
        lines.append("| — | — | *(none)* | — |")
    for e in gates["rng_log"]:
        lines.append(f"| `{e['phase']}` | `{e['entry']}` | `{e['caller']}` | "
                     f"`{e['args']}` |")
    lines += [
        "",
        "**Purity note D1-PN-1 (disclosed).** The single SUICA-attributed RNG "
        "call the five entries reach is "
        "`suica_core/v8_realtext_relation_field.py:198`, "
        "`frozen_random_directions(seed = spec.seed + 17)`, reached through "
        "`k2b.layout()` while S-4 asks the K2a-validated attenuation algebra "
        "for `r`. It draws the FROZEN GAUGE DIRECTIONS — a frozen operator "
        "constant of the deployed gauge, fixed by a frozen spec seed. It is "
        "not a world, not a response panel, not a card, and it is independent "
        "of every knob this leg varies (`share`, `phi`): the same draw happens "
        "for every arm K2b/K2c/K2d/K2e ever ran. No author, occasion, "
        "response or card is generated anywhere in this leg — the raising "
        "stubs above prove it, and `k2c.predicted_attenuation`'s own docstring "
        "(k2c:186-191) certifies the route: *\"Pure algebra: no world is "
        "generated.\"* The call is disclosed here rather than engineered "
        "around, because engineering around it would mean reimplementing "
        "published machinery and breaking rule 12.",
        "",
        "### The hash",
        "",
        f"- **sha256 (salted)** = `{sha}`",
        f"- construction: `{bundle_meta['hash_construction']}`",
        f"- salt: {bundle_meta['salt_bytes']} random bytes, "
        f"`{bundle_meta['salt_source']}`; stored ONLY in the bundle; never "
        "committed, never printed",
        f"- bundle: `{bundle_meta['bundle_path']}` "
        f"({bundle_meta['bundle_size_bytes']} bytes, gitignored via "
        "`.gitignore:2`)",
        f"- sealed at: `{bundle_meta['sealed_utc']}`",
        "",
        "### G2D — seal integrity, re-verified after writing",
        "",
        f"- bundle re-read from disk and re-hashed: "
        f"`{gates['g2d_recomputed_hash']}`",
        f"- equals the committed hash: **{gates['g2d_match']}**",
        f"- bundle carries the full prediction table: "
        f"**{gates['g2d_has_predictions']}** "
        f"({gates['g2d_n_entries']} entries)",
        f"- bundle carries the salt-handling statement: "
        f"**{gates['g2d_has_salt_statement']}**",
        f"- bundle carries the opening protocol: "
        f"**{gates['g2d_has_opening_protocol']}**",
        "",
        "### G3D — outcome (rule 16, trivial enumeration)",
        "",
        "| outcome | condition | fired |",
        "|---|---|---|",
        "| `SEAL-COMPLETE` | all five entries computed, sealed, hash committed "
        f"| {'**YES**' if gates['verdict'] == 'SEAL-COMPLETE' else 'no'} |",
        "| `SEAL-PARTIAL` | any entry uncomputable from published constants — "
        "named, sealed without it | "
        f"{'**YES**' if gates['verdict'] == 'SEAL-PARTIAL' else 'no'} |",
        "| `SEAL-FAIL` | protocol failure | "
        f"{'**YES**' if gates['verdict'] == 'SEAL-FAIL' else 'no'} |",
        "",
        f"**Verdict: `{gates['verdict']}`.** "
        f"{gates['verdict_note']}",
        "",
        "### Opening protocol (registered now, binding later)",
        "",
    ]
    for i, p in enumerate(OPENING_PROTOCOL, 1):
        lines.append(f"{i}. {p}")
    lines += [
        "",
        "### Timing and anomalies",
        "",
        f"- Part 0 written: `{timing['part0_utc']}`",
        f"- seal produced: `{timing['seal_utc']}`",
        f"- wall time, whole run: `{timing['wall_s']:.3f}` s "
        f"(budget: arithmetic only, target < 10 min)",
        f"- import of the K/L-line reuse graph: `{timing['import_s']:.3f}` s; "
        f"G0D provenance: `{timing['g0d_s']:.3f}` s; five entries: "
        f"`{timing['entries_s']:.3f}` s",
        "",
        "Anomalies, with timing:",
        "",
        "1. **`t≈0 s`, pre-run, protocol.** OP-31's `results/` artifact does "
        "not exist on this machine and `results/` is gitignored in full, so "
        "OP-31's seal of record is the tracked doc plus the tracked script "
        "constant. This does not block D1 — the fallback's storage model was "
        "pre-declared — but it means OP-31's own bundle is unverifiable here.",
        "2. **`t≈0 s`, pre-run, provenance.** κ is not in the file the "
        "registration cites, and its persisted sign is negative where the "
        "registration writes it positive. Both corrections are in Part 0.2; "
        "neither changes a number.",
        "3. **`t≈1 s`, purity harness, first draft.** A first purity harness "
        "poisoned `np.random.default_rng` unconditionally and crashed at "
        "IMPORT — inside `scipy.stats`, which calls `default_rng(615681484984984)` "
        "while building distribution docstrings. The harness was rewritten to "
        "ATTRIBUTE calls by stack frame instead of blanket-poisoning, so "
        "third-party RNG use is excluded and SUICA RNG use is logged rather "
        "than hidden. Corrected before any entry was computed.",
        "4. **`t≈1 s`, purity harness, second draft.** The generator guard "
        "list initially included `k2a.splits`, which raised on a legitimate "
        "call: `splits` is a deterministic occasion-INDEX partitioner "
        "(k2a:335-340), not a generator. It was removed from the guard list "
        "before any entry was computed; `build_world`, `response_panel`, "
        "`card` and `centered_channels` stayed.",
        "",
    ]
    return "\n".join(lines)


def do_seal() -> int:
    t_start = time.time()
    OUT.mkdir(parents=True, exist_ok=True)
    REPORT.parent.mkdir(parents=True, exist_ok=True)

    # --- import the reuse graph under the purity harness -------------------
    t0 = time.time()
    _PHASE["name"] = "import"
    k2c = _load("run_suica_m4_k2c_matched_pairs")
    k2e = _load("run_suica_m4_k2e_double_matching")
    l2 = _load("run_suica_m4_l2_threshold_continuum")
    mods = {"k2c": k2c, "k2e": k2e, "l2": l2,
            "k2b": k2c.k2b(), "k2a": k2c.k2b().k2a(), "l1": l2.l1()}
    import_s = time.time() - t0

    # --- G0D ---------------------------------------------------------------
    _PHASE["name"] = "G0D"
    t0 = time.time()
    values, prov = provenance_table()
    modchecks = module_constant_checks(mods, values)
    if not all(d["bit_exact"] for d in prov):
        bad = [d["constant"] for d in prov if not d["bit_exact"]]
        raise SystemExit(f"G0D FAIL — not bit-exact: {bad}")
    if not all(d["matches"] for d in modchecks):
        bad = [d["object"] for d in modchecks if not d["matches"]]
        raise SystemExit(f"G0D FAIL — source-object drift: {bad}")

    # --- G1D: arm the guards BEFORE any entry ------------------------------
    guards = install_generator_guards(mods)
    _PHASE["name"] = "G0D-algebra"
    algebra = algebra_round_trip(mods)
    if not all(d["r_bit_exact"] and d.get("V_person_bit_exact", True)
               for d in algebra):
        raise SystemExit("G0D FAIL — the attenuation/V_person algebra did not "
                         "round-trip bit-exactly against K2c/K2d")
    g0d_s = time.time() - t0

    # --- Part 0 to disk, BEFORE the seal (execution discipline) ------------
    part0_utc = datetime.now(timezone.utc).isoformat()
    REPORT.write_text(build_part0(prov, modchecks, algebra, guards, part0_utc),
                      encoding="utf-8")
    if not REPORT.exists() or REPORT.stat().st_size == 0:
        raise SystemExit("STOP: Part 0 was not written; the seal must not be "
                         "produced before it exists.")

    # --- the five entries ---------------------------------------------------
    _PHASE["name"] = "entries"
    t0 = time.time()
    l2_w3 = _read_json("results/m4_l2_threshold_continuum/decision.json")["leans"]["W-3"]
    band1 = s1_band_constant(l2_w3)
    entries = [entry_s1(values, band1), entry_s2(values),
               entry_s3(values, band1), entry_s4(mods, values),
               entry_s5(values)]
    entries_s = time.time() - t0

    # sanity WITHOUT disclosing values
    sane = []
    for e in entries:
        nums = _numbers(e)
        sane.append({"id": e["id"],
                     "all_finite": all(math.isfinite(x) for x in nums),
                     "n_numeric_fields": len(nums)})
    if not all(s["all_finite"] for s in sane):
        raise SystemExit("SEAL-FAIL: a non-finite value entered an entry")

    # --- the seal ----------------------------------------------------------
    _PHASE["name"] = "seal"
    salt = secrets.token_hex(32)
    sealed_utc = datetime.now(timezone.utc).isoformat()
    predictions = {"entries": entries,
                   "registration_commit": "4dad82e",
                   "sealed_utc": sealed_utc}
    sha = salted_hash(salt, predictions)
    bundle = {
        "leg": "SUICA D1 — prospective seal #2",
        "banner": BANNER,
        "registration": "docs/SUICA_DEFENSE_PHASE_PLAN.md, section D1, "
                        "commit 4dad82e",
        "protocol": {
            "authority": "OP-31 (docs/OP31_PROSPECTIVE_SEAL.md; "
                         "scripts/run_suica_op31_prospective_seal_v1.py:64-65)",
            "hash_mechanic_adopted": "op31:64-65 canonical sort_keys JSON sha256",
            "storage_model": "registration fallback "
                             "(SUICA_DEFENSE_PHASE_PLAN.md:24-28) — salted, "
                             "gitignored bundle, hash-only commit",
            "deviation": "OP-31 committed its plaintext because its target "
                         "text did not yet exist; D1's targets are runnable "
                         "today, so the plaintext is concealed and salted",
        },
        "salt_handling_statement":
            "The salt below is 32 cryptographically random bytes generated "
            "once at seal time by secrets.token_hex(32). It lives ONLY in "
            "this gitignored bundle. It was never committed, never printed to "
            "a terminal, and never quoted in the report. Its purpose is to "
            "make the committed hash non-invertible by dictionary search over "
            "plausible prediction tables. Losing this bundle, or this salt, "
            "VOIDS the seal — a lost bundle is not evidence for or against "
            "any entry.",
        "salt": salt,
        "hash_construction":
            "sha256((salt + json.dumps(predictions, sort_keys=True))"
            ".encode()).hexdigest()",
        "sha256_salted": sha,
        "predictions": predictions,
        "provenance_table": prov,
        "source_object_checks": modchecks,
        "algebra_round_trip": algebra,
        "purity": {"guards_installed": guards,
                   "generator_calls": GENERATOR_CALLS,
                   "foreign_rng_calls_excluded": FOREIGN_RNG["n"],
                   "rng_log": RNG_LOG},
        "opening_protocol": OPENING_PROTOCOL,
    }
    BUNDLE.write_text(json.dumps(bundle, indent=2, sort_keys=False) + "\n",
                      encoding="utf-8")
    try:
        os.chmod(BUNDLE, 0o600)
    except OSError:
        pass

    # --- G2D: re-verify from disk ------------------------------------------
    reread = json.loads(BUNDLE.read_text(encoding="utf-8"))
    recomputed = salted_hash(reread["salt"], reread["predictions"])
    g2d_match = (recomputed == sha)
    gates = {
        "n_generator_calls": len(GENERATOR_CALLS),
        "n_guards": len(guards),
        "n_foreign_rng": FOREIGN_RNG["n"],
        "rng_log": RNG_LOG,
        "g2d_recomputed_hash": recomputed,
        "g2d_match": g2d_match,
        "g2d_has_predictions": bool(reread.get("predictions", {}).get("entries")),
        "g2d_n_entries": len(reread.get("predictions", {}).get("entries", [])),
        "g2d_has_salt_statement": bool(reread.get("salt_handling_statement")),
        "g2d_has_opening_protocol": bool(reread.get("opening_protocol")),
    }
    n_ok = sum(1 for e in entries if e.get("id"))
    if not g2d_match or GENERATOR_CALLS:
        gates["verdict"] = "SEAL-FAIL"
        gates["verdict_note"] = ("the committed hash did not re-verify against "
                                 "the bundle, or a world generator fired.")
    elif n_ok == 5:
        gates["verdict"] = "SEAL-COMPLETE"
        gates["verdict_note"] = (
            "All five registered entries (S-1..S-5) were computable from "
            "PUBLISHED constants and PUBLISHED formulas alone, with zero world "
            "generations. No entry was dropped, so SEAL-PARTIAL does not fire. "
            "The hash re-verified against the bundle after writing.")
    else:
        gates["verdict"] = "SEAL-PARTIAL"
        gates["verdict_note"] = f"only {n_ok}/5 entries sealed."

    PUBLIC.write_text(json.dumps(
        {"leg": "D1", "sha256_salted": sha, "sealed_utc": sealed_utc,
         "verdict": gates["verdict"],
         "note": "public record; carries NO prediction value"},
        indent=2) + "\n", encoding="utf-8")

    structure = [{
        "id": e["id"], "grade": e["grade"], "config": e["config"],
        "formula": e["formula"], "formula_source": e["formula_source"],
        "sealed_what": _sealed_what(e),
        "band_kind": _band_kind(e),
    } for e in entries]

    meta = {"hash_construction": bundle["hash_construction"],
            "salt_bytes": 32, "salt_source": "secrets.token_hex(32)",
            "bundle_path": str(BUNDLE.relative_to(ROOT)),
            "bundle_size_bytes": BUNDLE.stat().st_size,
            "sealed_utc": sealed_utc}
    timing = {"part0_utc": part0_utc, "seal_utc": sealed_utc,
              "wall_s": time.time() - t_start, "import_s": import_s,
              "g0d_s": g0d_s, "entries_s": entries_s}
    with REPORT.open("a", encoding="utf-8") as fh:
        fh.write(build_part1(meta, structure, sha, gates, timing))

    # --- G2D sub-gate: mechanical leak check on the COMMITTED report --------
    leak = report_leak_check(predictions, REPORT.read_text(encoding="utf-8"))
    with REPORT.open("a", encoding="utf-8") as fh:
        fh.write("\n".join([
            "## Part 2 — leak check on this report (G2D sub-gate)",
            "",
            "Every prediction-bearing numeric leaf of the sealed table is "
            "searched for, verbatim, in the text of this report. The two "
            "published L2 edges disclosed in Part 0.2 are whitelisted; "
            "everything else must be absent.",
            "",
            f"- prediction-bearing values checked: "
            f"`{leak['n_prediction_bearing_values_checked']}`",
            f"- whitelisted (published L2 edges): "
            f"{', '.join('`' + w + '`' for w in leak['whitelisted'])}",
            f"- leaks found: **{leak['n_leaks']}**",
            f"- clean: **{leak['clean']}**",
            "",
            "The salt does not appear in this report; the bundle does not "
            "appear in git (`.gitignore:2`).",
            "",
        ]))
    if not leak["clean"]:
        print("SEAL-FAIL: prediction values leaked into the report:",
              [d["key"] for d in leak["leaks"]])
        return 1

    # terminal output carries NO sealed value
    print("D1 PROSPECTIVE SEAL")
    print("  verdict            :", gates["verdict"])
    print("  entries sealed     :", ", ".join(e["id"] for e in entries))
    print("  sha256 (salted)    :", sha)
    print("  G2D re-verify      :", g2d_match)
    print("  world generations  :", len(GENERATOR_CALLS))
    print("  guards armed       :", len(guards))
    print("  SUICA RNG calls    :",
          [f"{e['caller']} ({e['phase']})" for e in RNG_LOG] or "none")
    print("  foreign RNG (excl) :", FOREIGN_RNG["n"])
    print("  report leak check  :", leak["clean"],
          f"({leak['n_prediction_bearing_values_checked']} values checked, "
          f"{leak['n_leaks']} leaks)")
    print("  bundle             :", BUNDLE, f"({meta['bundle_size_bytes']} B)")
    print("  report             :", REPORT)
    print("  wall               : %.3f s" % timing["wall_s"])
    print("  sanity (no values) :", json.dumps(sane))
    return 0 if gates["verdict"] != "SEAL-FAIL" else 1


PREDICTION_BEARING_KEYS = {
    "predicted_per_boundary_rate", "boundary_z", "sigma_u2", "lo", "hi",
    "predicted_z_ratio", "predicted_z2_ratio", "predicted_lower_edge_delta",
    "predicted_upper_edge_delta", "predicted_window_width",
    "scale_vs_baseline", "lower_edge_interval", "upper_edge_interval",
    "predicted_level_term", "predicted_b_only_field_recovery",
    "r_predicted_attenuation", "V_person_design_share", "predicted_eta_hat",
    "cell_energy_sigma_b2",
}
# the two G0D constants that ARE, by identity, S-3's baseline edges; disclosed
# in Part 0.2 and therefore permitted to appear
LEAK_WHITELIST = {"4.238555648405859", "2.6977587972014083"}


def report_leak_check(predictions: dict, report_text: str) -> dict[str, Any]:
    """G2D sub-gate: no prediction-bearing value may appear in the COMMITTED
    report, except the two published L2 edges disclosed in Part 0.2."""
    found: list[dict[str, Any]] = []
    n_checked = 0

    def walk(o: Any, key: str | None = None) -> None:
        nonlocal n_checked
        if isinstance(o, dict):
            for k, v in o.items():
                walk(v, k)
        elif isinstance(o, list):
            for v in o:
                walk(v, key)
        elif isinstance(o, bool):
            return
        elif isinstance(o, (int, float)) and key in PREDICTION_BEARING_KEYS:
            n_checked += 1
            s = repr(o)
            if len(s) >= 6 and s in report_text and s not in LEAK_WHITELIST:
                found.append({"key": key, "rendering": s})

    walk(predictions)
    return {"n_prediction_bearing_values_checked": n_checked,
            "n_leaks": len(found), "leaks": found,
            "whitelisted": sorted(LEAK_WHITELIST), "clean": not found}


def _numbers(obj: Any) -> list[float]:
    out: list[float] = []
    if isinstance(obj, dict):
        for v in obj.values():
            out += _numbers(v)
    elif isinstance(obj, (list, tuple)):
        for v in obj:
            out += _numbers(v)
    elif isinstance(obj, bool):
        pass
    elif isinstance(obj, (int, float)):
        out.append(float(obj))
    return out


def _sealed_what(e: dict) -> str:
    return {
        "S-1": "3 per-boundary error rates (η ∈ {0, 0.5, 1}), each with "
               "σ_u²(η) and the boundary z, plus a named Δ-free companion",
        "S-2": "the z-ratio and z²-ratio, plus the ARI-drop direction claim",
        "S-3": "2 settings × (lower edge, upper edge, width, OPEN/EMPTY call)",
        "S-4": "the predicted b-only field recovery, its level term, and the "
               "(r, V_person) inputs",
        "S-5": "the predicted η̂ reading and the cell's σ_b²",
    }[e["id"]]


def _band_kind(e: dict) -> str:
    return {
        "S-1": "relative (derived from L2's W-3 record) / absolute for the "
               "degenerate cell",
        "S-2": "sign + strict ordering (no numeric tolerance)",
        "S-3": "interval, conjecture-grade + binary open/empty",
        "S-4": "absolute (derived from the 9-pair κ residual record)",
        "S-5": "absolute (the certified ±0.125) + carried pole-bias note",
    }[e["id"]]


def do_verify() -> int:
    """G2D standalone: re-verify the bundle against the hash in the report."""
    if not BUNDLE.exists():
        print("SEAL VOID: bundle missing at", BUNDLE)
        return 1
    b = json.loads(BUNDLE.read_text(encoding="utf-8"))
    recomputed = salted_hash(b["salt"], b["predictions"])
    ok = recomputed == b["sha256_salted"]
    print("recomputed:", recomputed)
    print("stored    :", b["sha256_salted"])
    print("MATCH     :", ok)
    return 0 if ok else 1


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--seal", action="store_true")
    ap.add_argument("--verify", action="store_true")
    a = ap.parse_args()
    if a.seal:
        raise SystemExit(do_seal())
    if a.verify:
        raise SystemExit(do_verify())
    ap.error("choose --seal or --verify")


if __name__ == "__main__":
    main()
